import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:4173');await page.waitForSelector('.card');await page.getByRole('button',{name:'Note · N',exact:true}).click();await page.locator('#edit-title').fill('Formatted note');await page.locator('#edit-title').press('Tab');await page.locator('#edit-body').fill('**Bold** and *italic*\n- list\n<script>window.injected=true</script>');await page.locator('#edit-body').press('Tab');assert.equal(await page.locator('.note-text strong').last().textContent(),'Bold');assert.equal(await page.evaluate(()=>!!window.injected),false);await page.getByRole('button',{name:'Close inspector'}).click();
 await page.getByRole('button',{name:'Connect ideas · C',exact:true}).click();await page.locator('.card').filter({hasText:'Formatted note'}).locator('.card-header').click();await page.locator('.card.task .card-header').first().click();assert.equal(await page.locator('[data-edge]').count(),2);
 await page.locator('.card').filter({hasText:'Formatted note'}).locator('.card-header').click();await page.locator('.card.task .card-header').first().click({modifiers:['Shift']});assert.equal(await page.locator('.card.selected').count(),2);await page.locator('#align-left').click();const xs=await page.locator('.card.selected').evaluateAll(els=>els.map(e=>e.style.left));assert.equal(xs[0],xs[1]);await page.getByRole('button',{name:'Close inspector'}).click();
 await page.locator('#media-input').setInputFiles({name:'reference.txt',mimeType:'text/plain',buffer:Buffer.from('Local reference content')});await page.waitForSelector('.card.file');const fileDownload=page.waitForEvent('download');await page.locator('.download-attachment').click();assert.equal((await fileDownload).suggestedFilename(),'reference.txt');await page.getByRole('button',{name:'Close inspector'}).click();
 await page.locator('#export-open').click();const download=page.waitForEvent('download');await page.locator('[data-export="json"]').click();const path=await (await download).path();await page.locator('#modal-close').click();
 await page.locator('#import-input').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":1,"boards":[]}')});assert.equal(await page.locator('.card.file').count(),1);assert.ok((await page.locator('#toast').textContent()).startsWith('Could not import'));
 await page.locator('#import-input').setInputFiles(path);await page.locator('#confirm-import').click();assert.equal(await page.locator('.card.file').count(),1);assert.equal(await page.locator('[data-edge]').count(),2);
 await page.locator('.card.file .card-header').click();await page.locator('#move-board').selectOption({label:'Visual references'});assert.equal(await page.locator('.card.file').count(),0);await page.locator('#boards .board-row').filter({hasText:'Visual references'}).click();assert.equal(await page.locator('.card.file').count(),1);
 await page.locator('#settings-open').click();await page.locator('#dark-setting').check();await page.locator('#save-settings').click();assert.equal(await page.locator('body.dark').count(),1);await page.waitForTimeout(700);await page.reload();await page.waitForSelector('.card.file');assert.equal(await page.locator('body.dark').count(),1);assert.deepEqual(errors,[]);
 console.log('PASS: safe note formatting, connectors, multi-selection/alignment, file download, valid/invalid imports, card transfer, persistent settings.');
}finally{await browser.close();}
