import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {board,card} from '../ui/model.js';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const b=board('Canvas components');b.view={x:80,y:60,zoom:.8};const f=card('frame',40,20);f.w=1050;f.h=650;f.title='Pitch frame';const x=card('sticky',120,120);x.title='Concept';x.body='Antigravity for earthlings';const y=card('shape',430,120);y.title='Delivery';const table=card('table',120,410);b.cards=[f,x,y,table];const w={version:1,active:b.id,boards:[b]};
async function closeInspector(){if(await page.locator('#inspector:not(.hidden)').count())await page.locator('#inspector-close').click();}
async function pick(id,shift=false){await page.locator(`.card[data-id="${id}"] .card-header`).click({modifiers:shift?['Shift']:[]});}
try{
 await page.goto('http://127.0.0.1:4173');await page.waitForSelector('.card');await page.locator('#import-input').setInputFiles({name:'canvas.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(w))});await page.locator('#confirm-import').click();
 assert.equal(await page.locator('.card.frame').count(),1);assert.equal(await page.locator('.card.sticky').count(),1);assert.equal(await page.locator('.card.shape').count(),1);
 await pick(table.id);await page.getByLabel('Row 2, column 1',{exact:true}).fill('Production');await page.getByLabel('Row 2, column 1',{exact:true}).press('Tab');assert.match(await page.locator('.canvas-table').textContent(),/Production/);await page.locator('#table-row').click();assert.equal(await page.locator('.canvas-table tr').count(),4);await closeInspector();
 await pick(y.id);await page.locator('#shape-kind').selectOption('ellipse');assert.equal(await page.locator('.shape-ellipse').count(),1);await closeInspector();
 await pick(x.id);await pick(y.id,true);await page.locator('[data-canvas-action="group"]').click();await closeInspector();await pick(x.id);assert.equal(await page.locator('.card.selected').count(),2);
 const before=await page.locator(`.card[data-id="${y.id}"]`).evaluate(el=>parseFloat(el.style.left));const r=await page.locator(`.card[data-id="${x.id}"] .card-header`).boundingBox();await page.mouse.move(r.x+50,r.y+20);await page.mouse.down();await page.mouse.move(r.x+90,r.y+60,{steps:5});await page.mouse.up();assert.ok(await page.locator(`.card[data-id="${y.id}"]`).evaluate(el=>parseFloat(el.style.left))>before+40);
 await page.locator('[data-canvas-action="lock"]').click();await closeInspector();await pick(x.id);assert.equal(await page.locator('#edit-title').isDisabled(),true);await page.locator('[data-canvas-action="unlock"]').click();assert.equal(await page.locator('#edit-title').isDisabled(),false);await closeInspector();await pick(y.id);await page.locator('[data-canvas-action="unlock"]').click();await page.locator('[data-canvas-action="ungroup"]').click();await closeInspector();
 await page.locator('#outline-open').click();await page.locator('#add-layer').click();await page.locator('.layer-row input').fill('Creative');await page.locator('.layer-row input').press('Tab');await page.locator('#outline-close').click();await pick(x.id);const layer=await page.locator('#object-layer option').last().getAttribute('value');await page.locator('#object-layer').selectOption(layer);await closeInspector();await page.locator('#outline-open').click();await page.locator('[data-layer-hide]').click();assert.equal(await page.locator('.card.sticky').count(),0);await page.locator('[data-layer-hide]').click();assert.equal(await page.locator('.card.sticky').count(),1);await page.locator('#outline-close').click();
 await page.locator('#minimap-open').click();assert.equal(await page.locator('#canvas-minimap').isVisible(),true);await page.locator('#canvas-minimap svg').click({position:{x:100,y:65}});
 await page.locator('#presentation-open').click();assert.match(await page.locator('#presentation-title').textContent(),/Pitch frame/);assert.equal(await page.locator('#presentation-stage .card.sticky').count(),1);await page.keyboard.press('Escape');assert.equal(await page.locator('#canvas-presentation').count(),0);
 await page.waitForTimeout(700);await page.reload();await page.waitForSelector('.card.sticky');assert.equal(await page.locator('.shape-ellipse').count(),1);assert.match(await page.locator('.canvas-table').textContent(),/Production/);await page.locator('#outline-open').click();assert.equal(await page.locator('.layer-row input').inputValue(),'Creative');await page.locator('#outline-close').click();
 // Toolbar remains usable on shorter screens: overflow scrolls rather than clipping tools.
 await page.getByRole('button',{name:'Sticky note',exact:true}).click();assert.equal(await page.locator('.card.sticky').count(),2);await closeInspector();await page.locator('#undo').click();assert.equal(await page.locator('.card.sticky').count(),1);
 await page.locator('#fit').click();await page.locator('#minimap-open').click();await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/canvas-components.png'});// Selection works in the empty portion of a frame as well as outside frames.
 await page.locator('#import-input').setInputFiles({name:'canvas.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(w))});await page.locator('#confirm-import').click();
 const sx=await page.locator(`.card[data-id="${x.id}"]`).boundingBox(),sy=await page.locator(`.card[data-id="${y.id}"]`).boundingBox();await page.mouse.move(sx.x-8,sx.y-8);await page.mouse.down();await page.mouse.move(sy.x+sy.width+8,Math.max(sx.y+sx.height,sy.y+sy.height)+8,{steps:6});await page.mouse.up();assert.equal(await page.locator('.card.selected').count(),2);
 await page.locator('[data-canvas-action="distribute-x"]').click();await closeInspector();await pick(x.id);await page.locator(`.card[data-id="${x.id}"] .card-header`).click({button:'right'});assert.equal(await page.locator('#canvas-context').isVisible(),true);await page.locator('#canvas-context [data-canvas-action="lock"]').click();assert.equal(await page.locator('#edit-title').isDisabled(),true);await page.locator('[data-canvas-action="unlock"]').click();await closeInspector();
 assert.deepEqual(errors,[]);
 console.log('PASS: tables, shapes, grouping and drag, locks, layer visibility, minimap, presentation, persistence, toolbar and undo.');
}finally{await browser.close();}
