import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:4173');await page.waitForSelector('.card');assert.equal(await page.locator('.card').count(),5);await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/atelier-workspace.png'});
 await page.getByRole('button',{name:'Note · N',exact:true}).click();await page.locator('#edit-title').fill('Test research');await page.locator('#edit-title').press('Tab');await page.locator('#edit-body').fill('A durable idea for an offline workspace.');await page.locator('#edit-body').press('Tab');await page.locator('#edit-tags').fill('test, research');await page.locator('#edit-tags').press('Tab');await page.locator('#comment-text').fill('Review this tomorrow');await page.getByRole('button',{name:'Add annotation',exact:true}).click();assert.equal(await page.locator('.comment').count(),1);
 await page.getByRole('button',{name:'Close inspector'}).click();await page.waitForTimeout(800);await page.reload();await page.waitForSelector('.card');assert.equal(await page.locator('.card').count(),6);
 await page.locator('#search-open').click();await page.locator('#search-query').fill('durable');assert.equal(await page.locator('.search-result').count(),1);await page.locator('.search-result').click();assert.equal(await page.locator('#edit-title').inputValue(),'Test research');
 await page.getByRole('button',{name:'Duplicate',exact:true}).click();assert.equal(await page.locator('.card').count(),7);await page.getByRole('button',{name:'Delete',exact:true}).click();assert.equal(await page.locator('.card').count(),6);await page.locator('#undo').click();assert.equal(await page.locator('.card').count(),7);await page.locator('#redo').click();assert.equal(await page.locator('.card').count(),6);
 const target=page.locator('.card').filter({hasText:'Test research'});let r=await target.locator('.card-header').boundingBox();const old=await target.evaluate(el=>parseFloat(el.style.left));await page.mouse.move(r.x+50,r.y+15);await page.mouse.down();await page.mouse.move(r.x+130,r.y+80,{steps:5});await page.mouse.up();assert.ok(await target.evaluate(el=>parseFloat(el.style.left))>old+50);
 const size=await target.evaluate(el=>parseFloat(el.style.width));r=await target.locator('.resize-handle').boundingBox();await page.mouse.move(r.x+5,r.y+5);await page.mouse.down();await page.mouse.move(r.x+60,r.y+45,{steps:5});await page.mouse.up();assert.ok(await target.evaluate(el=>parseFloat(el.style.width))>size+30);
 await page.getByRole('button',{name:'Close inspector'}).click();await page.getByRole('button',{name:'To-do list · T',exact:true}).click();await page.getByRole('button',{name:'Add task',exact:true}).click();assert.equal(await page.locator('.task-edit').count(),2);
 await page.getByRole('button',{name:'Close inspector'}).click();await page.locator('#templates-open').click();await page.locator('[data-template="film"]').click();assert.equal(await page.locator('.card').count(),6);assert.equal(await page.locator('#board-title').textContent(),'Film pre-production');
 await page.getByRole('button',{name:'Nested board',exact:true}).click();await page.locator('#new-name').fill('Shot references');await page.locator('#create-board').click();assert.equal(await page.locator('#board-title').textContent(),'Shot references');await page.locator('#breadcrumbs [data-nav]').first().click();assert.equal(await page.locator('.card.board').count(),1);
 await page.locator('#media-input').setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')});await page.waitForSelector('.card.image');
 await page.getByRole('button',{name:'Close inspector'}).click();await page.locator('#export-open').click();const downloadEvent=page.waitForEvent('download');await page.locator('[data-export="json"]').click();assert.equal((await downloadEvent).suggestedFilename(),'atelier-workspace.json');await page.locator('#modal-close').click();
 await page.getByRole('button',{name:'Sketch',exact:true}).click();r=await page.locator('#sketch-canvas').boundingBox();await page.mouse.move(r.x+20,r.y+20);await page.mouse.down();await page.mouse.move(r.x+80,r.y+80,{steps:5});await page.mouse.up();await page.locator('#save-sketch').click();assert.equal(await page.locator('.card.sketch').count(),1);
 await page.waitForTimeout(600);await page.reload();await page.waitForSelector('.card.sketch');await page.locator('#fit').click();await page.screenshot({path:'artifacts/atelier-film-board.png'});assert.deepEqual(errors,[]);console.log('PASS: editing, persistence, search, duplicate/delete/undo, drag/resize, tasks, templates, hierarchy, images, export, sketch. No page errors.');
}finally{await browser.close();}
