import {styleVars} from './palette.js';
import {drawing} from './drawing.js';
import * as C from './canvas-model.js';
import {content as canvasContent,createCanvasUX} from './canvas-ui.js';
let canvasUX;
import {videoPlayer,importVideo} from './video.js';
import {isModel,openViewer} from './viewer.js';
import {uid,clone,card,board,History,validate,removeCards,duplicateCards,markdown,templates,recipes,applyRecipe,applyTemplate,initial} from './model.js';
import {icon,hydrate} from './icons.js';
import * as storage from './storage.js';
import {renderMarkdown} from './format.js';
import * as T from './timeline.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const history=new History();let workspace,selected=new Set(),connectMode=false,connectFrom=null,space=false,saveTimer,toastTimer,clipboard=[],saveChain=Promise.resolve(),loadFailed=false,activeItem=null,connectSpot=null,nudged=0;
const colors={paper:'#ffffff',sage:'#edf0ea',sand:'#f6f1e8',rose:'#f4ecea',sky:'#eaeef3',stone:'#f2f2ef'};
const current=()=>workspace.boards.find(b=>b.id===workspace.active);
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function dirty(){current().updated=Date.now();$('#save-status').innerHTML='<i></i> Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(persist,400);}
function persist(){
 if(loadFailed)return;
 const snapshot=clone(workspace);saveChain=saveChain.catch(()=>{}).then(()=>storage.save(snapshot)).then(()=>{$('#save-status').innerHTML='<i></i> Saved';return true;}).catch(e=>{$('#save-status').textContent='Save failed';toast(e.message||String(e));return false;});return saveChain;
}
function change(fn){history.push(workspace);fn();dirty();render();}
function navigate(id){if(!workspace.boards.some(b=>b.id===id))return;workspace.active=id;selected.clear();connectFrom=null;activeItem=null;dirty();render();}
function ancestors(b){const list=[];while(b){list.unshift(b);b=workspace.boards.find(x=>x.id===b.parent);}return list;}
function render(){renderSidebar();renderBoard();renderCards();renderInspector();$('#undo').disabled=!history.past.length;$('#redo').disabled=!history.future.length;canvasUX?.render();}
function renderSidebar(){
 const rows=[];function tree(parent,depth=0){workspace.boards.filter(b=>b.parent===parent).forEach(b=>{rows.push(`<button class="board-row ${depth?'child':''} ${b.id===workspace.active?'active':''}" data-board="${b.id}" style="padding-left:${12+Math.min(depth,5)*16}px">${icon('board')}<span class="name">${esc(b.name)}</span><span class="count">${b.cards.length}</span></button>`);tree(b.id,depth+1);});}tree(null);
 $('#boards').innerHTML=rows.join('');$('#boards').querySelectorAll('[data-board]').forEach(el=>el.onclick=()=>navigate(el.dataset.board));
}
function renderBoard(){const b=current();$('#board-title').textContent=b.name;$('#board-description').textContent=b.description;$('#breadcrumbs').innerHTML=`${icon('home')}<span>/</span>`+ancestors(b).map((a,i,arr)=>`<button data-nav="${a.id}" class="${i===arr.length-1?'current':''}">${esc(a.name)}</button>`).join('<span>/</span>');$('#breadcrumbs').querySelectorAll('[data-nav]').forEach(el=>el.onclick=()=>navigate(el.dataset.nav));view();$('#empty').style.display=b.cards.length?'none':'block';}
function view(){const v=current().view;$('#world').style.transform=`translate(${v.x}px,${v.y}px) scale(${v.zoom})`;$('#zoom-label').textContent=Math.round(v.zoom*100)+'%';$('#canvas').style.backgroundPosition=`${v.x}px ${v.y}px`;$('#canvas').style.backgroundSize=`${22*v.zoom}px ${22*v.zoom}px`;canvasUX?.drawMap();}
function media(c){if(!c.media&&!c.localVideo)return `<div class="card-body">Drop a file here, or use the inspector to upload.</div>`;if(c.type==='video')return `<div class="card-body">${esc(c.filename||'Video')}<br><button class="play-native button">Play with libmpv</button></div>`;return `<img class="card-media" alt="${esc(c.title)}" src="${esc(c.media)}" draggable="false">`;}
// ── Timeline cards ──────────────────────────────────────────────────────────
// A timeline card draws a left-to-right ruler in timecode or calendar days, and other cards on the board connect to it as
// clips. Time arithmetic and integrity rules live in timeline.js; this section draws the card and handles its gestures.
const TL_PAD=16,trackWidth=c=>c.w-2-TL_PAD*2;
const cardTitle=c=>c.type==='board'?workspace.boards.find(b=>b.id===c.boardId)?.name||c.title:c.title;
const along=(tl,u)=>((u-tl.start)/(tl.end-tl.start)*100).toFixed(4)+'%';
// A zero-length connection is a marker: a flag that opens to the right, or to the left near the end of the range.
const itemClass=(tl,i,s)=>`tl-item ${i.len?'':'marker'} ${!i.len&&(i.at-tl.start)/(tl.end-tl.start)>.78?'flip':''} tint-${colors[s.color]?s.color:'paper'} ${activeItem?.item===i.id?'active':''} ${selected.has(s.id)?'linked':''}`;
const itemStyle=(tl,i)=>`left:${along(tl,i.at)};${i.len?`width:${(i.len/(tl.end-tl.start)*100).toFixed(4)}%;`:''}top:calc(${i.lane}*100%/var(--lanes) + 3px);height:calc(100%/var(--lanes) - 6px)`;
// The connection last touched: Delete and the arrow keys act on it while its timeline is the only selected card.
function activeEntry(){if(!activeItem||selected.size!==1||!selected.has(activeItem.timeline))return null;const c=current().cards.find(c=>c.id===activeItem.timeline),item=c?.timeline?.items.find(i=>i.id===activeItem.item);return item?{c,item}:null;}
function timelineBody(c){
 const tl=c.timeline,b=current(),t=T.ticks(tl,trackWidth(c)),lanes=T.laneCount(tl),now=T.today(),shown=tl.items.filter(i=>T.visible(tl,i)),hidden=tl.items.length-shown.length;
 const clip=i=>{const s=b.cards.find(x=>x.id===i.card);if(!s)return '';const thumb=['image','sketch'].includes(s.type)?s.media:s.preview,title=esc(cardTitle(s));
  return `<div class="${itemClass(tl,i,s)}" data-item="${i.id}" data-source="${s.id}" style="${itemStyle(tl,i)}" title="${title} · ${esc(T.span(tl,i))}"><span class="tl-grip l"></span>${thumb?`<img src="${esc(thumb)}" alt="" draggable="false">`:`<span class="tl-kind">${icon(s.type)}</span>`}<span class="tl-text"><span class="tl-name">${title}</span><span class="tl-when">${esc(T.when(tl,i))}</span></span><span class="tl-grip r"></span></div>`;};
 return `<div class="tl ${tl.mode} ${(c.h-100)/lanes<34?'compact':''}" data-timeline="${c.id}"><div class="tl-ruler">${t.minor.map(u=>`<i style="left:${along(tl,u)}"></i>`).join('')}${t.major.map(m=>`<span style="left:${along(tl,m.u)}">${esc(m.label)}</span>`).join('')}</div><div class="tl-lanes" style="--lanes:${lanes}">${t.major.map(m=>`<i class="tl-grid" style="left:${along(tl,m.u)}"></i>`).join('')}${tl.mode==='date'&&now>=tl.start&&now<tl.end?`<i class="tl-today" style="left:${along(tl,now)};width:${(100/(tl.end-tl.start)).toFixed(4)}%" title="Today"></i>`:''}${shown.map(clip).join('')}</div><div class="tl-cursor" hidden><b></b></div></div><div class="tl-foot"><span>${esc(T.summary(tl))}</span><span>${tl.items.length?`${tl.items.length} connected${hidden?` · ${hidden} outside this range`:''}`:'Drag a card here to connect it'}</span></div>`;
}
// Where a card dropped on a timeline is placed on the board: just below it, under the pointer.
const beneath=(hit,e)=>({x:position(e).x-125,y:hit.c.y+hit.c.h+50});
function timeAt(c,zone,x){const tl=c.timeline,r=zone.getBoundingClientRect(),u=tl.start+(x-r.left)/r.width*(tl.end-tl.start),date=tl.mode==='date';return Math.max(tl.start,Math.min(date?tl.end-1:tl.end,date?Math.floor(u):T.snap(tl,u,trackWidth(c))));}
function laneAt(c,zone,y){const r=zone.querySelector('.tl-lanes').getBoundingClientRect(),n=T.laneCount(c.timeline);return Math.max(0,Math.min(n-1,Math.floor((y-r.top)/r.height*n)));}
// The topmost timeline whose track lies under a screen point, with the time and lane at that point.
function timelineAt(x,y,skip){
 const zone=[...$('#cards').querySelectorAll('.card.timeline .tl')].filter(z=>{const r=z.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom&&!skip?.has(z.dataset.timeline);}).at(-1),c=zone&&current().cards.find(c=>c.id===zone.dataset.timeline);
 return c&&!C.locked(current(),c)?{c,zone,at:timeAt(c,zone,x),lane:laneAt(c,zone,y)}:null;
}
function showCursor(zone,tl,at){const cursor=zone.querySelector('.tl-cursor'),share=(at-tl.start)/(tl.end-tl.start);cursor.hidden=false;cursor.style.left=share*100+'%';cursor.classList.toggle('flip',share>.82);cursor.firstChild.textContent=T.label(at,tl);}
// Marks the timeline a drag would land on, or clears the mark when called with nothing.
function dropHint(hit){document.querySelectorAll('.tl.drop').forEach(z=>{if(z!==hit?.zone){z.classList.remove('drop');z.querySelector('.tl-cursor').hidden=true;}});if(hit){hit.zone.classList.add('drop');showCursor(hit.zone,hit.c.timeline,hit.at);}}
function markSelection(){
 $('#cards').querySelectorAll('.card').forEach(x=>x.classList.toggle('selected',selected.has(x.dataset.id)));
 $('#cards').querySelectorAll('.tl-item').forEach(x=>{x.classList.toggle('linked',selected.has(x.dataset.source));x.classList.toggle('active',activeItem?.item===x.dataset.item);});
 $('#edges').querySelectorAll('[data-link]').forEach(x=>x.classList.toggle('linked',selected.has(x.dataset.source)||activeItem?.item===x.dataset.link));
}
// Connects cards to a timeline as part of the caller's undo step. Returns the new connections.
function attachItems(c,cards,at,lane=0){
 const tl=c.timeline,lanes=T.laneCount(tl),made=cards.filter(s=>T.connectable(s.type)).slice(0,T.MAX_ITEMS-tl.items.length).map((s,k)=>T.connect(tl,uid(),s.id,at,undefined,lane+k));
 if(made.length){makeRoom(c,lanes);selected=new Set([c.id]);activeItem={timeline:c.id,item:made.at(-1).id};}
 return made;
}
// A timeline card grows when an action adds a lane, so clips stay readable; a size the user chose is otherwise left alone.
function makeRoom(c,lanesBefore){const lanes=T.laneCount(c.timeline);if(lanes>lanesBefore)c.h=Math.max(c.h,lanes*44+102);}
function connected(c,made,cards){toast(made.length?`${made.length===1?`“${cardTitle(cards.find(s=>s.id===made[0].card))}”`:`${made.length} cards`} connected at ${T.label(made[0].at,c.timeline)}.`:c.timeline.items.length>=T.MAX_ITEMS?`A timeline holds at most ${T.MAX_ITEMS} connections.`:'Columns and timelines cannot be placed on a timeline.');}
function attach(c,cards,at,lane){let made=[];if(cards.some(s=>T.connectable(s.type))&&c.timeline.items.length<T.MAX_ITEMS)change(()=>made=attachItems(c,cards,at,lane));connected(c,made,cards);}
function pickAsset(c,at,lane){
 const b=current(),choices=b.cards.filter(x=>T.connectable(x.type));if(!choices.length){toast('Add a card to this board first, then connect it.');return;}
 modal('Connect a card.',`It lands at ${T.label(at,c.timeline)} on “${c.title}”. You can drag it along the timeline afterwards.`,`<input class="text-input" id="asset-query" placeholder="Filter this board’s cards…" aria-label="Filter cards"><div class="search-results" id="asset-results"></div>`);
 const draw=()=>{const q=$('#asset-query').value.toLowerCase().trim(),list=choices.filter(x=>(cardTitle(x)+' '+x.type+' '+x.filename+' '+x.tags.join(' ')).toLowerCase().includes(q));
  $('#asset-results').innerHTML=list.map(x=>{const n=c.timeline.items.filter(i=>i.card===x.id).length;return `<button class="search-result" data-asset="${x.id}">${icon(x.type)}<span><strong>${esc(cardTitle(x))}</strong><small>${esc(x.type)}${x.filename?' · '+esc(x.filename):''}${n?` · already here ${n===1?'once':n+' times'}`:''}</small></span></button>`;}).join('')||'<p class="inline-note">No cards match.</p>';
  $('#asset-results').querySelectorAll('[data-asset]').forEach(el=>el.onclick=()=>{$('#modal').close();attach(c,[b.cards.find(x=>x.id===el.dataset.asset)],at,lane);});};
 $('#asset-query').oninput=draw;draw();$('#asset-query').focus();
}
function bindTimeline(el,c){
 const tl=c.timeline,zone=el.querySelector('.tl'),lanes=el.querySelector('.tl-lanes');
 zone.onpointermove=e=>{if(!e.buttons)showCursor(zone,tl,timeAt(c,zone,e.clientX));};zone.onpointerleave=()=>{if(!zone.classList.contains('drop'))zone.querySelector('.tl-cursor').hidden=true;};
 zone.ondblclick=e=>{e.stopPropagation();if(C.locked(current(),c))return;if(!e.target.closest('.tl-item'))pickAsset(c,timeAt(c,zone,e.clientX),laneAt(c,zone,e.clientY));};
 const glow=(node,on)=>{$('#edges').querySelector(`[data-link="${node.dataset.item}"]`)?.classList.toggle('hover',on);$('#cards').querySelector(`.card[data-id="${node.dataset.source}"]`)?.classList.toggle('tl-source',on);};
 lanes.querySelectorAll('.tl-item').forEach(node=>{const item=tl.items.find(i=>i.id===node.dataset.item);
  node.addEventListener('pointerdown',e=>itemPointer(e,c,item,node,lanes));node.onmouseenter=()=>glow(node,true);node.onmouseleave=()=>glow(node,false);
  node.ondblclick=e=>{e.stopPropagation();const s=current().cards.find(x=>x.id===item.card),r=$('#canvas').getBoundingClientRect(),v=current().view;selected=new Set([s.id]);activeItem=null;if((s.x+s.w)*v.zoom+v.x<0||s.x*v.zoom+v.x>r.width||(s.y+s.h)*v.zoom+v.y<0||s.y*v.zoom+v.y>r.height)focusCard(s);render();};});
}
// Drag a clip sideways to retime it, by an edge to trim it, and up or down to change lane.
function itemPointer(e,c,item,node,lanes){
 if(C.locked(current(),c))return;
 if(e.button!==0||connectMode||space||e.shiftKey||e.target.closest('button'))return;
 e.preventDefault();e.stopPropagation();selected=new Set([c.id]);activeItem={timeline:c.id,item:item.id};markSelection();renderInspector();
 const tl=c.timeline,grip=e.target.closest('.tl-grip'),mode=grip?(grip.classList.contains('l')?'in':'out'):'move',start={x:e.clientX,y:e.clientY},o={...item},source=current().cards.find(x=>x.id===item.card),count=T.laneCount(tl);let before,moved=false;
 node.setPointerCapture(e.pointerId);
 const move=ev=>{
  if(!moved&&Math.abs(ev.clientX-start.x)+Math.abs(ev.clientY-start.y)<3)return;if(!moved){before=clone(workspace);moved=true;}
  const r=lanes.getBoundingClientRect(),to=u=>T.snap(tl,u+(ev.clientX-start.x)/r.width*(tl.end-tl.start),trackWidth(c));
  if(mode==='move'){item.at=o.len<=tl.end-tl.start?Math.max(tl.start,Math.min(tl.end-o.len,to(o.at))):to(o.at);item.lane=Math.max(0,Math.min(count-1,o.lane+Math.round((ev.clientY-start.y)/(r.height/count))));}
  else if(mode==='out')item.len=Math.max(o.at+1,Math.min(Math.max(tl.end,o.at+o.len),to(o.at+o.len)))-o.at; // trimming stops at one frame or one day
  else{item.at=Math.min(o.at+o.len-1,Math.max(Math.min(tl.start,o.at),to(o.at)));item.len=o.at+o.len-item.at;}
  T.place(tl,item);node.style.cssText=itemStyle(tl,item);node.className=itemClass(tl,item,source);node.querySelector('.tl-when').textContent=T.when(tl,item);node.title=`${cardTitle(source)} · ${T.span(tl,item)}`;renderEdges();
 };
 const end=()=>{node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',end);node.removeEventListener('pointercancel',end);if(moved){history.push(before);makeRoom(c,count);dirty();render();}};
 node.addEventListener('pointermove',move);node.addEventListener('pointerup',end);node.addEventListener('pointercancel',end);
}
function linkPaths(b){
 return b.cards.filter(c=>c.type==='timeline'&&c.timeline.links&&C.visible(b,c)).map(c=>{const tl=c.timeline;return tl.items.filter(i=>T.visible(tl,i)).map(i=>{const s=b.cards.find(x=>x.id===i.card);if(!s||!C.visible(b,s))return '';
  const share=Math.max(0,Math.min(1,(i.at+i.len/2-tl.start)/(tl.end-tl.start))),x2=c.x+1+TL_PAD+share*trackWidth(c),above=s.y+s.h/2<c.y+c.h/2,x1=s.x+s.w/2,y1=above?s.y+s.h:s.y,y2=above?c.y:c.y+c.h,d=Math.max(30,Math.abs(y2-y1)/2)*(above?1:-1);
  return `<g class="tl-link ${selected.has(s.id)||activeItem?.item===i.id?'linked':''}" data-link="${i.id}" data-source="${s.id}"><path d="M${x1} ${y1}C${x1} ${y1+d} ${x2} ${y2-d} ${x2} ${y2}" fill="none" stroke="#8a8a90" stroke-dasharray="4 4"/><circle cx="${x2}" cy="${y2}" r="3" fill="#8a8a90"/></g>`;}).join('');}).join('');
}
function timelineFields(c){
 const tl=c.timeline,b=current(),date=tl.mode==='date',rows=[...tl.items].sort((x,y)=>x.at-y.at||x.lane-y.lane);
 return `<div class="field"><label for="tl-mode">Runs left to right in</label><select id="tl-mode"><option value="timecode" ${date?'':'selected'}>Timecode</option><option value="date" ${date?'selected':''}>Calendar dates</option></select></div>
 ${date?`<div class="field-pair"><div class="field"><label for="tl-start">From</label><input id="tl-start" type="date" min="1000-01-01" max="9999-12-31" value="${T.isoDate(tl.start)}"></div><div class="field"><label for="tl-end">To</label><input id="tl-end" type="date" min="1000-01-01" max="9999-12-31" value="${T.isoDate(tl.end-1)}"></div></div>`:`<div class="field"><label for="tl-rate">Frame rate</label><select id="tl-rate">${T.RATES.map(r=>`<option value="${r.id}" ${r===T.rateOf(tl)?'selected':''}>${r.label}</option>`).join('')}</select></div><div class="field-pair"><div class="field"><label for="tl-start">Start timecode</label><input id="tl-start" value="${T.timecode(tl.start,tl)}" spellcheck="false"></div><div class="field"><label for="tl-end">Duration</label><input id="tl-end" value="${T.timecode(tl.end-tl.start,tl)}" spellcheck="false"></div></div><p class="inline-note">Type HH:MM:SS:FF, MM:SS, seconds, or frames as 48f.</p>`}
 <label class="check"><input id="tl-links" type="checkbox" ${tl.links?'checked':''}> Draw lines to connected cards</label>
 <div class="label">Connected cards</div><div id="tl-items">${rows.map(i=>{const s=b.cards.find(x=>x.id===i.card),title=esc(cardTitle(s));return `<div class="tl-row ${activeItem?.item===i.id?'active':''}" data-row="${i.id}"><div class="tl-row-head"><button class="tl-row-name" title="Highlight on the timeline">${icon(s.type)}<span>${title}</span></button><button class="tl-row-remove" aria-label="Disconnect ${title}">${icon('close')}</button></div><div class="field-pair">${date?`<input type="date" data-in value="${T.isoDate(i.at)}" aria-label="First day of ${title}"><input type="date" data-out value="${T.isoDate(i.at+i.len-1)}" aria-label="Last day of ${title}">`:`<input data-in value="${T.timecode(i.at,tl)}" spellcheck="false" aria-label="In point of ${title}"><input data-out value="${T.timecode(i.at+i.len,tl)}" spellcheck="false" aria-label="Out point of ${title}">`}</div></div>`;}).join('')||'<p class="inline-note">Nothing connected yet.</p>'}</div>
 <button id="tl-connect" class="button">${icon('plus')} Connect a card</button><p class="inline-note">Or drag any card, or a file, onto the timeline. Drag a clip to retime it, its edges to trim it, and up or down to change lane. ${date?'Here the first day moves a clip and the last day sets how long it runs.':'Here the in point moves a clip and the out point sets how long it runs; make them equal for a marker.'} Delete disconnects the highlighted clip and leaves its card on the board.</p>`;
}
// Timeline fields re-render the inspector, so apply the edit after the browser has moved focus and then restore that focus.
function settle(fn){setTimeout(()=>{const a=document.activeElement,row=a?.closest?.('[data-row]'),key=a?.id?'#'+a.id:row?`[data-row="${row.dataset.row}"] ${a.matches('[data-in]')?'[data-in]':a.matches('[data-out]')?'[data-out]':'.tl-row-name'}`:null;fn();if(key&&$('#inspector').contains(a)===false)$('#inspector').querySelector(key)?.focus();},0);}
function bindTimelineFields(c){
 const tl=c.timeline,date=tl.mode==='date',read=el=>date?T.parseDate(el.value):T.parseTimecode(el.value,tl),edit=fn=>settle(()=>change(fn));
 const reject=()=>settle(()=>{toast(date?'Choose a date between the years 1000 and 9999.':'Use HH:MM:SS:FF, MM:SS, seconds, or frames as 48f.');renderInspector();});
 $('#tl-mode').onchange=e=>{const mode=e.target.value;edit(()=>T.setMode(tl,mode));};
 if($('#tl-rate'))$('#tl-rate').onchange=e=>{const rate=e.target.value;edit(()=>T.setRate(tl,rate));};
 $('#tl-start').onchange=e=>{const v=read(e.target);if(v===null)return reject();edit(()=>date?T.setRange(tl,v,Math.max(tl.end,v+1)):T.setRange(tl,v,v+tl.end-tl.start,true));};
 $('#tl-end').onchange=e=>{const v=read(e.target);if(v===null||(!date&&v<1))return reject();edit(()=>date?T.setRange(tl,Math.min(tl.start,v),v+1):T.setRange(tl,tl.start,tl.start+v));};
 $('#tl-links').onchange=e=>{const on=e.target.checked;edit(()=>tl.links=on);};
 $('#tl-connect').onclick=()=>pickAsset(c,T.nextFree(tl));
 $('#tl-items').querySelectorAll('[data-row]').forEach(row=>{const i=tl.items.find(x=>x.id===row.dataset.row);
  row.querySelector('.tl-row-name').onclick=()=>{activeItem={timeline:c.id,item:i.id};markSelection();renderInspector();$('#inspector').querySelector(`[data-row="${i.id}"] .tl-row-name`)?.focus();};
  row.querySelector('.tl-row-remove').onclick=()=>change(()=>{tl.items=tl.items.filter(x=>x!==i);activeItem=null;});
  row.querySelector('[data-in]').onchange=e=>{const v=read(e.target);if(v===null)return reject();edit(()=>{i.at=v;T.place(tl,i);});};
  row.querySelector('[data-out]').onchange=e=>{const v=read(e.target);if(v===null)return reject();edit(()=>{i.len=date?v-i.at+1:v-i.at;T.place(tl,i);});};});
}
function timelineSvg(c,b){
 const tl=c.timeline,x0=c.x+1+TL_PAD,w=trackWidth(c),top=c.y+44,height=Math.max(20,c.h-100),n=T.laneCount(tl),lane=height/n,X=u=>x0+Math.max(0,Math.min(1,(u-tl.start)/(tl.end-tl.start)))*w,t=T.ticks(tl,w);
 return `<rect x="${x0}" y="${top+24}" width="${w}" height="${height}" rx="4" fill="#f2f2ef" stroke="#e4e4e0"/>`+t.minor.map(u=>`<path d="M${X(u)} ${top+19}v5" stroke="#d3d3ce"/>`).join('')+t.major.map(m=>`<path d="M${X(m.u)} ${top+4}V${top+24+height}" stroke="#e4e4e0"/><text x="${X(m.u)+5}" y="${top+15}" font-size="10" fill="#6b6b72">${esc(m.label)}</text>`).join('')
  +tl.items.filter(i=>T.visible(tl,i)).map(i=>{const s=b.cards.find(x=>x.id===i.card);if(!s)return '';const x=X(i.at),y=top+24+i.lane*lane+3;return `<rect x="${x}" y="${y}" width="${Math.max(3,X(i.at+i.len)-x)}" height="${Math.max(4,lane-6)}" rx="3" fill="${s.style?.fill||colors[s.color]||'#fff'}" stroke="#d3d3ce"/><text x="${x+7}" y="${y+Math.max(4,lane-6)/2+4}" font-size="10" fill="#18181b">${esc(cardTitle(s))} · ${esc(T.when(tl,i))}</text>`;}).join('')
  +`<text x="${x0}" y="${c.y+c.h-12}" font-size="10" fill="#6b6b72">${esc(T.summary(tl))}</text>`;
}
function renderCards(){
 const b=current();$('#cards').innerHTML=b.cards.filter(c=>C.visible(b,c)).map(c=>{
 let content=canvasContent(c);
 if(content!==null){}
 else if(c.type==='task'){const done=c.items.filter(i=>i.done).length;content=`<div class="task-list">${c.items.map(i=>`<label class="task-item ${i.done?'done':''}"><input type="checkbox" data-task="${i.id}" ${i.done?'checked':''}><span>${esc(i.text)}</span></label>`).join('')}</div><div class="progress-track"><i style="width:${c.items.length?done/c.items.length*100:0}%"></i></div>`;}
 else if(['image','video','sketch'].includes(c.type))content=media(c);
 else if(c.type==='board'){const sub=workspace.boards.find(x=>x.id===c.boardId);content=`<div class="board-cover" data-enter="${c.boardId}">${icon('board')}</div><div class="board-sub">${sub?.cards.length||0} ideas inside ${icon('arrow')}</div>`;}
 else if(c.type==='link'){let domain='Add a website address';try{domain=new URL(c.url).hostname;}catch{}content=`<div class="card-body"><span class="link-domain">${esc(domain)}</span>${esc(c.body)}<br>${c.url?'<button class="open-link">Open link ↗</button>':''}</div>`;}
 else if(c.type==='model')content=`${c.preview?`<img class="model-preview" alt="${esc(c.title)}" src="${esc(c.preview)}">`:''}<div class="card-body">${esc(c.filename)}<br><button class="open-model button">Explore in 3D</button></div>`;
 else if(c.type==='file')content=`<div class="card-body">${esc(c.filename||'No file attached')}<br>${esc(c.body)}${(c.media||c.localAttachment)?'<br><button class="open-link download-attachment">Save attachment ↓</button>':''}</div>`;
 else if(c.type==='timeline')content=timelineBody(c);
 else content=`<div class="card-body ${c.type==='note'?'note-text':''}">${c.type==='note'?renderMarkdown(c.body):esc(c.body)}</div>`;
 const footer=c.tags.length||c.comments.length?`<div class="card-footer">${c.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}${c.comments.length?`<span class="comment-count">${c.comments.length} ${icon('comment')}</span>`:''}</div>`:'';
 return `<article class="card ${c.type} color-${Object.keys(colors).includes(c.color)?c.color:'paper'} ${selected.has(c.id)?'selected':''}" data-id="${c.id}" style="left:${c.x}px;top:${c.y}px;width:${c.w}px;height:${c.h}px;z-index:${C.container(c)?0:2+b.cards.indexOf(c)};${styleVars(c)}"><div class="card-header"><span class="card-type">${icon(c.type)}</span><span class="card-title">${C.locked(b,c)?'🔒 ':''}${esc(c.type==='board'?workspace.boards.find(b=>b.id===c.boardId)?.name:c.title)}</span><button class="card-more" title="Edit card" aria-label="Edit ${esc(c.title)}">${icon('more')}</button></div>${content}${footer}<div class="resize-handle"></div></article>`;
 }).join('');
 $('#cards').querySelectorAll('.card').forEach(el=>{
 const c=b.cards.find(c=>c.id===el.dataset.id);
 el.addEventListener('pointerdown',e=>cardPointer(e,c,el));
 el.ondblclick=e=>{if(e.target.closest('input,video,button'))return;if(c.type==='board')navigate(c.boardId);else if(c.type==='model')showModel(c);else if(c.type==='video')showVideo(c);else{selected=new Set([c.id]);renderInspector();}};
 el.querySelector('.card-more').onclick=e=>{e.stopPropagation();selected=new Set([c.id]);renderCards();renderInspector();};
 el.querySelectorAll('[data-task]').forEach(x=>{x.disabled=C.locked(b,c);x.onchange=()=>change(()=>c.items.find(i=>i.id===x.dataset.task).done=x.checked);});
 if(c.type==='board')el.querySelector('[data-enter]').onclick=()=>navigate(c.boardId);
 if(c.type==='link')el.querySelector('.open-link')?.addEventListener('click',()=>{try{Promise.resolve(storage.openLink(c.url)).catch(e=>toast(e.message||e));}catch(e){toast(e.message);}});
 if(c.type==='video')el.querySelector('.play-native')?.addEventListener('click',()=>showVideo(c));
 if(c.type==='model')el.querySelector('.open-model').onclick=()=>showModel(c);
 if(c.type==='file')el.querySelector('.download-attachment')?.addEventListener('click',()=>{(c.localAttachment?window.__TAURI__.core.invoke('save_managed_attachment',{id:c.localAttachment,name:c.filename}):storage.saveAttachment(c.filename||'attachment',c.media)).then(ok=>{if(ok)toast('Attachment saved.');}).catch(e=>toast(e.message||e));});
 if(c.type==='timeline')bindTimeline(el,c);
 });renderEdges();canvasUX?.render();
}
function renderEdges(){const b=current();$('#edges').innerHTML=`<defs><marker id="arrowhead" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0l10 5-10 5" fill="#8a8a90"/></marker></defs>`+b.edges.map(e=>{const f=b.cards.find(c=>c.id===e.from),t=b.cards.find(c=>c.id===e.to);if(!f||!t||!C.visible(b,f)||!C.visible(b,t))return '';const right=t.x>=f.x,x1=f.x+(right?f.w:0),y1=f.y+f.h/2,x2=t.x+(right?0:t.w),y2=t.y+t.h/2,d=Math.max(60,Math.abs(x2-x1)/2)*(right?1:-1);return `<g data-edge="${e.id}"><path class="edge-path" marker-end="${e.arrow===false?'':'url(#arrowhead)'}" d="${e.style==='straight'?`M${x1} ${y1}L${x2} ${y2}`:e.style==='elbow'?`M${x1} ${y1}H${(x1+x2)/2}V${y2}H${x2}`:`M${x1} ${y1}C${x1+d} ${y1} ${x2-d} ${y2} ${x2} ${y2}`}"/><text class="edge-label" x="${(x1+x2)/2}" y="${(y1+y2)/2-10}" text-anchor="middle">${esc(e.label)}</text></g>`;}).join('')+linkPaths(b);$('#edges').querySelectorAll('[data-edge]').forEach(el=>el.ondblclick=()=>editEdge(el.dataset.edge));}
function position(e){const r=$('#canvas').getBoundingClientRect(),v=current().view;return {x:(e.clientX-r.left-v.x)/v.zoom,y:(e.clientY-r.top-v.y)/v.zoom};}
function cardPointer(e,c,el){
 if(e.button!==0||e.target.closest('button,input,video,a')||space)return;
 if(c.type==='frame'&&!e.target.closest('.card-header,.resize-handle')&&!connectMode)return;
 if(C.locked(current(),c)){selected=new Set([c.id]);markSelection();renderInspector();return;}
 if(c.groupId&&!e.shiftKey&&!connectMode){selected=new Set(C.members(current(),new Set([c.id])).map(c=>c.id));activeItem=null;markSelection();renderInspector();}
 if(connectMode){e.preventDefault();const zone=c.type==='timeline'&&e.target.closest('.tl'),spot=zone?{at:timeAt(c,zone,e.clientX),lane:laneAt(c,zone,e.clientY)}:null;
  if(!connectFrom){connectFrom=c.id;connectSpot=spot;toast(c.type==='timeline'?'Now click the card to place on this timeline.':current().cards.some(x=>x.type==='timeline')?'Select another card, or click a timeline to place this card on it.':'Select another card to connect.');}
  else if(connectFrom!==c.id){const from=current().cards.find(x=>x.id===connectFrom),done=()=>{connectFrom=null;connectSpot=null;connectMode=false;renderTools();};
   if(c.type==='timeline'&&T.connectable(from?.type)){done();attach(c,[from],spot?spot.at:T.nextFree(c.timeline),spot?.lane);}
   else if(from?.type==='timeline'&&T.connectable(c.type)){const at=connectSpot?connectSpot.at:T.nextFree(from.timeline),lane=connectSpot?.lane;done();attach(from,[c],at,lane);}
   else{change(()=>current().edges.push({id:uid(),from:connectFrom,to:c.id,label:''}));done();toast('Connected. Double-click the line to label it.');}}
  return;}
 if(e.shiftKey){selected.has(c.id)?selected.delete(c.id):selected.add(c.id);renderCards();renderInspector();return;}
 if(activeItem||!selected.has(c.id)){const known=selected.has(c.id);activeItem=null;if(!known)selected=new Set([c.id]);markSelection();renderInspector();}
 const resize=e.target.closest('.resize-handle');
 if(!resize&&!e.target.closest('.card-header')&&c.type!=='column')return;
 e.preventDefault();e.stopPropagation();const start={x:e.clientX,y:e.clientY},before=clone(workspace),original=(resize?C.members(current(),selected):C.movable(current(),selected)).map(x=>({id:x.id,x:x.x,y:x.y,w:x.w,h:x.h}));let moved=false;
 // Cards released over a timeline's track connect to it at that time and return to where they were.
 const carried=resize?[]:current().cards.filter(x=>selected.has(x.id)&&T.connectable(x.type)),skip=new Set(original.map(o=>o.id)),target=ev=>carried.length?timelineAt(ev.clientX,ev.clientY,skip):null;
 el.setPointerCapture(e.pointerId);
 const move=ev=>{const dx=(ev.clientX-start.x)/current().view.zoom,dy=(ev.clientY-start.y)/current().view.zoom;if(Math.abs(dx)+Math.abs(dy)<3&&!moved)return;moved=true;for(const o of original){const target=current().cards.find(x=>x.id===o.id);if(resize){target.w=Math.max(target.type==='timeline'?360:140,Math.min(3000,o.w+dx));target.h=Math.max(target.type==='timeline'?150:65,Math.min(3000,o.h+dy));}else{target.x=Math.max(-90000,Math.min(90000,o.x+dx));target.y=Math.max(-90000,Math.min(90000,o.y+dy));}const node=$(`[data-id="${o.id}"]`);node.style.left=target.x+'px';node.style.top=target.y+'px';node.style.width=target.w+'px';node.style.height=target.h+'px';}renderEdges();dropHint(target(ev));};
 const end=ev=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',end);dropHint(null);if(moved){history.push(before);const hit=ev.type==='pointerup'?target(ev):null;
  if(hit){for(const o of original){const t=current().cards.find(x=>x.id===o.id);t.x=o.x;t.y=o.y;}connected(hit.c,attachItems(hit.c,carried,hit.at,hit.lane),carried);}
  else if($('#snap-setting')?.checked||localStorage.getItem('atelier-snap')==='yes')for(const o of original){const t=current().cards.find(x=>x.id===o.id);t.x=Math.round(t.x/22)*22;t.y=Math.round(t.y/22)*22;}dirty();render();}};
 el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);
}
function add(type,point){if(type==='video'&&storage.isNative()){importVideo().then(file=>{if(file)change(()=>{const c=card('video',100,100);c.localVideo=file.id;c.filename=file.filename;c.title=file.filename.replace(/\.[^.]+$/,'');current().cards.push(c);selected=new Set([c.id]);});}).catch(e=>toast(String(e)));return;}if(type==='model'){$('#media-input').click();return;}if(type==='image'||type==='video'||type==='file'){$('#media-input').dataset.type=type;$('#media-input').click();return;}if(type==='sketch'){sketch();return;}if(type==='board'){newBoard(true);return;}
 const p=point||{x:(180-current().view.x)/current().view.zoom,y:(100-current().view.y)/current().view.zoom};change(()=>{const c=card(type,p.x,p.y);current().cards.push(c);selected=new Set([c.id]);});}
function renderTools(){const names={note:'Note · N',task:'To-do list · T',image:'Image',video:'Video · libmpv',link:'Link · L',board:'Nested board',column:'Column',heading:'Heading',sketch:'Sketch',file:'File or video',model:'3D model + resources',timeline:'Timeline · timecode or dates',sticky:'Sticky note',shape:'Shape',frame:'Frame',table:'Table',connect:'Connect ideas · C'};$('#tools').innerHTML=Object.entries(names).map(([type,label],i)=>`${i===9?'<div class="tool-separator"></div>':''}<button class="tool ${type==='connect'&&connectMode?'active':''}" data-type="${type}" data-label="${label}" title="${label}" aria-label="${label}">${icon(type)}</button>`).join('');$('#tools').querySelectorAll('[data-type]').forEach(el=>el.onclick=()=>{if(el.dataset.type==='connect'){connectMode=!connectMode;connectFrom=null;renderTools();if(connectMode)toast('Click the first card, then the second.');}else add(el.dataset.type);});}
function editField(c,key,value){history.push(workspace);c[key]=value;dirty();renderCards();renderSidebar();$('#undo').disabled=false;}
function renderInspector(){
 const el=$('#inspector'),cards=current().cards.filter(c=>selected.has(c.id));el.classList.toggle('hidden',!cards.length);if(!cards.length)return;
 const close=`<button class="icon-button" id="inspector-close" aria-label="Close inspector">${icon('close')}</button>`;
 if(cards.length>1){el.innerHTML=`<div class="inspector-head"><span>Selection</span>${close}</div><div class="selection-info">${cards.length} ideas selected</div><div class="select-actions"><button class="button" id="align-left">Align left</button><button class="button" id="align-top">Align top</button><button class="button" id="arrange">Arrange in a grid</button><button class="button" id="duplicate">Duplicate</button><button class="button danger" id="delete-card">Delete selected</button></div>`;$('#align-left').onclick=()=>change(()=>C.align(current(),selected,'left'));$('#align-top').onclick=()=>change(()=>C.align(current(),selected,'top'));$('#arrange').onclick=()=>arrange(cards);}
 else{
 const c=cards[0];el.innerHTML=`<div class="inspector-head"><span>${esc(c.type.charAt(0).toUpperCase()+c.type.slice(1))}</span>${close}</div><div class="field"><label for="edit-title">Title</label><input id="edit-title" maxlength="1000" value="${esc(c.type==='board'?workspace.boards.find(x=>x.id===c.boardId)?.name:c.title)}"></div>${c.type==='timeline'?timelineFields(c):''}${!['image','video','sketch','board','task','timeline'].includes(c.type)?`<div class="field"><label for="edit-body">${c.type==='heading'?'Subtitle':'Notes'}</label>${c.type==='note'?'<div class="format-tools"><button data-format="bold" title="Bold"><strong>B</strong></button><button data-format="italic" title="Italic"><em>I</em></button><button data-format="list" title="Bulleted list">• List</button><button data-format="heading" title="Heading">H</button></div>':''}<textarea id="edit-body">${esc(c.body)}</textarea></div>`:''}
 ${c.type==='link'?`<div class="field"><label for="edit-url">Website address</label><input id="edit-url" placeholder="https://…" value="${esc(c.url)}"></div>`:''}
 ${c.type==='task'?`<div class="label">Checklist</div><div id="task-editor">${c.items.map(i=>`<div class="task-edit" data-item="${i.id}"><input type="checkbox" ${i.done?'checked':''} aria-label="Complete task"><input class="text-input" value="${esc(i.text)}" aria-label="Task text"><button aria-label="Remove task">${icon('close')}</button></div>`).join('')}</div><button id="add-task" class="button">${icon('plus')} Add task</button><br><br>`:''}
 ${['image','video','file','sketch'].includes(c.type)?`<button id="replace-media" class="button">${icon(c.type==='sketch'?'pen':'image')} ${c.type==='sketch'?'Edit sketch':'Replace file'}</button><p class="inline-note">Finder imports preserve original files on this Mac. JSON backups include embedded previews; managed originals and large videos must be copied separately when migrating.</p>`:''}
 ${c.type==='model'?'<button id="inspect-model" class="button">Explore in 3D</button><p class="inline-note">Import a model together with its MTL and textures. Files stay embedded locally.</p>':''}
 ${c.localAttachment||c.localVideo?'<button id="save-original" class="button">Save original file ↓</button><br><br>':''}
 ${c.type==='board'?'<button id="open-sub-board" class="button">Open board →</button><br><br>':''}
 <div class="field"><label>Card color</label><div class="swatches">${Object.entries(colors).map(([key,col])=>`<button class="swatch swatch-${key} ${key===c.color?'active':''}" data-color="${key}" title="${key}" aria-label="${key}"></button>`).join('')}</div></div>
 <div class="field"><label for="edit-tags">Tags, separated by commas</label><input id="edit-tags" value="${esc(c.tags.join(', '))}" placeholder="inspiration, research"></div>
 <div class="field"><label for="move-board">Move to board</label><select id="move-board">${workspace.boards.map(b=>`<option value="${b.id}" ${b.id===current().id?'selected':''}>${esc(b.name)}</option>`).join('')}</select></div>
 <div class="inspector-actions"><button id="duplicate" class="button">${icon('copy')} Duplicate</button><button id="delete-card" class="button danger">${icon('trash')} Delete</button></div>
 <div class="comments"><div class="label">Personal annotations</div>${c.comments.map((a,i)=>`<div class="comment">${esc(a.text)}<button data-remove-comment="${i}" aria-label="Remove annotation">×</button><small>${esc(a.author)} · ${new Date(a.date).toLocaleDateString()}</small></div>`).join('')}<div class="field"><textarea id="comment-text" placeholder="Leave a thought…" style="min-height:80px" aria-label="Annotation"></textarea></div><button id="add-comment" class="button">Add annotation</button><p class="inline-note">These annotations stay on your device.</p></div>`;
 $('#edit-title').onchange=e=>{const title=e.target.value.trim()||'Untitled';if(c.type==='board')change(()=>{workspace.boards.find(x=>x.id===c.boardId).name=title;c.title=title;});else editField(c,'title',title);};
 if($('#edit-body'))$('#edit-body').onchange=e=>editField(c,'body',e.target.value);
 if(c.type==='timeline')bindTimelineFields(c);
 el.querySelectorAll('[data-format]').forEach(btn=>btn.onclick=()=>{const input=$('#edit-body'),start=input.selectionStart,end=input.selectionEnd,selection=input.value.slice(start,end)||'text',format=btn.dataset.format,insert=format==='bold'?'**'+selection+'**':format==='italic'?'*'+selection+'*':format==='list'?'\n- '+selection:'\n## '+selection;input.setRangeText(insert,start,end,'select');editField(c,'body',input.value);input.focus();});
 if($('#edit-url'))$('#edit-url').onchange=e=>{try{let value=e.target.value;if(value&&!/^https?:\/\//i.test(value))value='https://'+value;if(value&&!['http:','https:'].includes(new URL(value).protocol))throw Error('Use an http or https address.');editField(c,'url',value);e.target.value=value;}catch(e){toast(e.message);}};
 $('#edit-tags').onchange=e=>editField(c,'tags',e.target.value.split(',').map(t=>t.trim()).filter(Boolean).slice(0,20));
 el.querySelectorAll('[data-color]').forEach(btn=>btn.onclick=()=>change(()=>{c.color=btn.dataset.color;delete c.style;}));
 if(c.type==='task'){$('#add-task').onclick=()=>change(()=>c.items.push({id:uid(),text:'New task',done:false}));el.querySelectorAll('[data-item]').forEach(row=>{const i=c.items.find(x=>x.id===row.dataset.item);row.querySelector('[type=checkbox]').onchange=e=>change(()=>i.done=e.target.checked);row.querySelector('.text-input').onchange=e=>{history.push(workspace);i.text=e.target.value;dirty();renderCards();};row.querySelector('button').onclick=()=>change(()=>c.items=c.items.filter(x=>x.id!==i.id));});}
 $('#move-board').onchange=e=>change(()=>{const target=workspace.boards.find(b=>b.id===e.target.value),source=current();removeCards(source,new Set([c.id]));delete c.layerId;delete c.groupId;delete c.sectionId;if(c.timeline)c.timeline.items=[];T.prune(source.cards);target.cards.push(c);selected.clear();});
 $('#add-comment').onclick=()=>{const text=$('#comment-text').value.trim();if(text)change(()=>c.comments.push({author:localStorage.getItem('atelier-name')||'You',text,date:Date.now()}));};el.querySelectorAll('[data-remove-comment]').forEach(btn=>btn.onclick=()=>change(()=>c.comments.splice(Number(btn.dataset.removeComment),1)));
 if($('#replace-media'))$('#replace-media').onclick=()=>{if(c.type==='sketch')sketch(c);else if(c.type==='video'&&storage.isNative()){importVideo().then(file=>{if(file)change(()=>{c.localVideo=file.id;delete c.localAttachment;c.media='';c.filename=file.filename;c.title=file.filename;});}).catch(e=>toast(String(e)));}else{$('#media-input').dataset.replace=c.id;$('#media-input').dataset.type=c.type;$('#media-input').click();}};
 if($('#save-original'))$('#save-original').onclick=()=>window.__TAURI__.core.invoke('save_managed_attachment',{id:c.localAttachment||c.localVideo,name:c.filename}).then(ok=>{if(ok)toast('Original saved.');}).catch(e=>toast(String(e)));
 if($('#inspect-model'))$('#inspect-model').onclick=()=>showModel(c);
 if($('#open-sub-board'))$('#open-sub-board').onclick=()=>navigate(c.boardId);
 }
 $('#inspector-close').onclick=()=>{selected.clear();renderCards();renderInspector();};$('#duplicate').onclick=()=>change(()=>selected=new Set(duplicateCards(current(),selected)));$('#delete-card').onclick=deleteSelected;canvasUX?.inspector();
}
function deleteSelected(){if(!selected.size)return;change(()=>{removeCards(current(),new Set(C.members(current(),selected).map(c=>c.id)));selected.clear();});}
function arrange(cards=current().cards.filter(c=>c.type!=='heading'&&!C.container(c)&&c.type!=='timeline')){cards=cards.filter(c=>C.visible(current(),c)&&!C.locked(current(),c));change(()=>{const w=Math.max(260,...cards.map(c=>c.w))+30,h=Math.max(200,...cards.map(c=>c.h))+30;cards.forEach((c,i)=>{c.x=80+(i%3)*w;c.y=80+Math.floor(i/3)*h;});});}
let viewerCleanup;
function showVideo(c){const dialog=modal(c.title,'Native color-managed playback · metadata reported by libmpv', '<div id="video-player"></div>');dialog.classList.add('model-dialog');viewerCleanup=videoPlayer($('#video-player'),c);dialog.addEventListener('close',()=>{viewerCleanup?.();viewerCleanup=null;dialog.classList.remove('model-dialog');},{once:true});}
function showModel(c){const dialog=modal(c.title,'Drag to orbit · right-drag to pan · scroll to zoom. Select model, MTL and textures together when importing.', '<div id="model-viewer"></div>');dialog.classList.add('model-dialog');viewerCleanup=openViewer($('#model-viewer'),c,(view,preview)=>change(()=>{c.modelView=view;c.preview=preview;}));dialog.addEventListener('close',()=>{viewerCleanup?.();viewerCleanup=null;dialog.classList.remove('model-dialog');},{once:true});}
function modal(title,subtitle,body){viewerCleanup?.();viewerCleanup=null;const el=$('#modal');el.classList.remove('model-dialog');el.innerHTML=`<div class="modal-header"><div><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div><button id="modal-close" class="icon-button" aria-label="Close dialog">${icon('close')}</button></div>${body}`;$('#modal-close').onclick=()=>el.close();if(!el.open)el.showModal();return el;}
function newBoard(nested=false){modal('A space for your next idea.','Give it a name, then make it yours.',`<div class="field"><label for="new-name">Board name</label><input id="new-name" placeholder="Untitled board" maxlength="1000"></div><div class="field"><label for="template-select">Starting point</label><select id="template-select">${templates.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select></div><div class="modal-footer"><button class="button primary" id="create-board">Create board</button></div>`);$('#new-name').focus();$('#create-board').onclick=()=>{const name=$('#new-name').value.trim()||'Untitled board',template=$('#template-select').value;$('#modal').close();change(()=>{const parent=current(),b=applyTemplate(board(name,nested?parent.id:null),template);workspace.boards.push(b);if(nested){const c=card('board',(180-parent.view.x)/parent.view.zoom,(100-parent.view.y)/parent.view.zoom);c.title=name;c.boardId=b.id;parent.cards.push(c);}workspace.active=b.id;selected.clear();});};$('#new-name').onkeydown=e=>{if(e.key==='Enter')$('#create-board').click();};}
function showTemplates(){
 modal('Choose your starting point.','44 starter-pack templates, four project recipes, and the original Atelier boards.',`<div class="template-filters"><input id="template-search" placeholder="Search templates or media…" aria-label="Search templates"><select id="template-family" aria-label="Template family"><option value="">All disciplines</option>${[...new Set(templates.map(t=>t.family).filter(Boolean))].map(f=>`<option value="${f}">${f}</option>`).join('')}<option value="recipes">Project recipes</option></select></div><div id="template-results" class="template-grid"></div><p class="inline-note">Templates are editable scaffolds. Frames and presentation are available from the canvas. Animatic playback, layered PSD editing, and executable node graphs remain roadmap items. Add a Timeline card from the toolbar to lay cards out against timecode or dates.</p>`);
 const draw=()=>{const q=$('#template-search').value.toLowerCase(),family=$('#template-family').value;
 const choices=[...templates.map(t=>({...t,recipe:false})),...recipes.map(r=>({id:r.id,name:r.id.replaceAll('_',' '),label:`${r.template_ids.length} linked boards for a complete project.`,family:'recipes',icon:'board',recipe:true}))].filter(t=>(!family||t.family===family)&&[t.name,t.label,...(t.tags||[]),...(t.media||[])].join(' ').toLowerCase().includes(q));
 $('#template-results').innerHTML=choices.length?choices.map(t=>`<button class="template" data-template="${t.id}" data-recipe="${t.recipe}">${icon(t.icon)}<strong>${esc(t.name)}</strong><small>${esc(t.family||'Atelier original')}</small><p>${esc(t.label)}</p></button>`).join(''):'<p>No matching templates.</p>';
 $('#template-results').querySelectorAll('[data-template]').forEach(el=>el.onclick=()=>{const t=choices.find(t=>t.id===el.dataset.template);$('#modal').close();change(()=>{if(t.recipe)applyRecipe(workspace,t.id);else{const b=applyTemplate(board(t.id==='blank'?'Untitled board':t.name),t.id);workspace.boards.push(b);workspace.active=b.id;}selected.clear();});fit();});};
 $('#template-search').oninput=draw;$('#template-family').onchange=draw;draw();$('#template-search').focus();
}
function projectFields(){const b=current();if(!b.projectFields)return;modal('Project details.','Editable fields from this template.',`${Object.entries(b.projectFields).map(([key,value])=>`<div class="field"><label>${esc(key.replaceAll('_',' '))}</label><input data-project-field="${esc(key)}" value="${esc(value)}" maxlength="10000"></div>`).join('')}<div class="modal-footer"><button id="save-project-fields" class="button primary">Save details</button></div>`);$('#save-project-fields').onclick=()=>{const entries=[...$('#modal').querySelectorAll('[data-project-field]')].map(el=>[el.dataset.projectField,el.value]);$('#modal').close();change(()=>b.projectFields=Object.fromEntries(entries));};}

function renameBoard(){modal('Board details','A title and a little context.',`<div class="field"><label for="rename-title">Title</label><input id="rename-title" maxlength="1000" value="${esc(current().name)}"></div><div class="field"><label for="rename-description">Description</label><textarea id="rename-description">${esc(current().description)}</textarea></div><div class="modal-footer"><button class="button primary" id="rename-save">Save changes</button></div>`);$('#rename-save').onclick=()=>{const name=$('#rename-title').value.trim()||'Untitled board',description=$('#rename-description').value;$('#modal').close();change(()=>{current().name=name;current().description=description;});};}
function boardMenu(){modal('Make this space work for you.','Board tools',`<div class="export-options"><button class="export-option" id="rename-board">${icon('pen')} Rename & describe</button>${current().projectFields?'<button class="export-option" id="project-fields">Project details</button>':''}<button class="export-option" id="organize-board">${icon('layout')} Arrange cards in a grid</button><button class="export-option" id="copy-board">${icon('copy')} Duplicate this board</button><button class="export-option" id="clear-edges">${icon('connect')} Remove all connections</button><button class="export-option" id="delete-board">${icon('trash')} Delete this board and its nested boards</button></div>`);$('#rename-board').onclick=renameBoard;if($('#project-fields'))$('#project-fields').onclick=projectFields;$('#organize-board').onclick=()=>{$('#modal').close();arrange();};$('#clear-edges').onclick=()=>{$('#modal').close();change(()=>current().edges=[]);};$('#copy-board').onclick=()=>{$('#modal').close();change(()=>{const b=clone(current());b.id=uid();b.name+=' — copy';const map=new Map();b.cards.forEach(c=>{const old=c.id;c.id=uid();map.set(old,c.id);});b.edges=b.edges.map(e=>({...e,id:uid(),from:map.get(e.from),to:map.get(e.to)}));C.remap(b.cards,map,uid);b.cards.forEach(c=>{if(c.timeline)T.recopy(c.timeline,uid,map);});if(b.presentationOrder)b.presentationOrder=b.presentationOrder.map(id=>map.get(id));workspace.boards.push(b);workspace.active=b.id;selected.clear();});};$('#delete-board').onclick=()=>{modal('Delete this board?','Its nested boards and all their cards will also be removed. You can undo this.',`<div class="modal-footer"><button id="confirm-delete-board" class="button danger">Delete board</button></div>`);$('#confirm-delete-board').onclick=()=>{$('#modal').close();change(()=>{const doomed=new Set([current().id]);let grow=true;while(grow){grow=false;for(const b of workspace.boards)if(doomed.has(b.parent)&&!doomed.has(b.id)){doomed.add(b.id);grow=true;}}workspace.boards=workspace.boards.filter(b=>!doomed.has(b.id));for(const b of workspace.boards){const deleted=new Set(b.cards.filter(c=>doomed.has(c.boardId)).map(c=>c.id));removeCards(b,deleted);}if(!workspace.boards.length)workspace.boards.push(board());workspace.active=workspace.boards[0].id;selected.clear();});};};}
function editEdge(id){const e=current().edges.find(e=>e.id===id);modal('Connect the dots.','Give this connection a little meaning.',`<div class="field"><label for="edge-label">Label</label><input id="edge-label" value="${esc(e.label)}"></div><div class="field"><label for="edge-style">Line style</label><select id="edge-style">${['curve','straight','elbow'].map(s=>`<option ${s===(e.style||'curve')?'selected':''}>${s}</option>`).join('')}</select><label><input id="edge-arrow" type="checkbox" ${e.arrow===false?'':'checked'} style="width:auto"> Arrowhead</label></div><div class="modal-footer"><button class="button danger" id="edge-delete">Delete connection</button><button class="button primary" id="edge-save">Save label</button></div>`);$('#edge-save').onclick=()=>{const label=$('#edge-label').value,style=$('#edge-style').value,arrow=$('#edge-arrow').checked;$('#modal').close();change(()=>{e.label=label;e.style=style;e.arrow=arrow;});};$('#edge-delete').onclick=()=>{$('#modal').close();change(()=>current().edges=current().edges.filter(x=>x.id!==id));};}
function showSearch(){modal('Find the thread.','Search across all boards, notes, tasks, and tags.',`<input class="text-input" id="search-query" placeholder="Search your workspace…" aria-label="Search workspace"><div class="search-results" id="search-results"></div>`);$('#search-query').focus();const query=()=>{const q=$('#search-query').value.toLowerCase().trim(),results=[];if(q)for(const b of workspace.boards){if((b.name+' '+b.description).toLowerCase().includes(q))results.push({b,title:b.name,type:'board'});for(const c of b.cards)if((c.title+' '+c.body+' '+(c.cells||[]).flat().join(' ')+' '+c.tags.join(' ')+' '+c.items.map(i=>i.text).join(' ')+' '+c.comments.map(i=>i.text).join(' ')+' '+c.url).toLowerCase().includes(q))results.push({b,c,title:c.title,type:c.type});}$('#search-results').innerHTML=results.slice(0,100).map((r,i)=>`<button class="search-result" data-result="${i}">${icon(r.type)}<span><strong>${esc(r.title)}</strong><small>${esc(r.b.name)} · ${r.type}</small></span></button>`).join('')||`<p class="inline-note">${q?'No ideas found. Try another word.':'Your next discovery is a search away.'}</p>`;$('#search-results').querySelectorAll('[data-result]').forEach(btn=>btn.onclick=()=>{const r=results[btn.dataset.result];$('#modal').close();navigate(r.b.id);if(r.c){selected=new Set([r.c.id]);focusCard(r.c);render();}});};$('#search-query').oninput=query;query();}
function focusCard(c){const v=current().view,r=$('#canvas').getBoundingClientRect();v.x=r.width/2-(c.x+c.w/2)*v.zoom;v.y=r.height/2-(c.y+c.h/2)*v.zoom;view();dirty();}
function zoom(next,x,y){const v=current().view,r=$('#canvas').getBoundingClientRect();x??=r.width/2;y??=r.height/2;next=Math.min(2,Math.max(.2,next));v.x=x-(x-v.x)*next/v.zoom;v.y=y-(y-v.y)*next/v.zoom;v.zoom=next;view();dirty();}
function fit(){const cs=current().cards.filter(c=>C.visible(current(),c));if(!cs.length)return;const minX=Math.min(...cs.map(c=>c.x)),minY=Math.min(...cs.map(c=>c.y)),maxX=Math.max(...cs.map(c=>c.x+c.w)),maxY=Math.max(...cs.map(c=>c.y+c.h)),r=$('#canvas').getBoundingClientRect(),v=current().view;v.zoom=Math.min(1.2,Math.max(.2,Math.min((r.width-170)/(maxX-minX),(r.height-110)/(maxY-minY))));v.x=95-minX*v.zoom;v.y=35-minY*v.zoom;view();dirty();}
function svgExport(b){
 const cs=b.cards.filter(c=>C.visible(b,c)),minX=Math.min(0,...cs.map(c=>c.x))-25,minY=Math.min(0,...cs.map(c=>c.y))-25,maxX=Math.max(800,...cs.map(c=>c.x+c.w))+25,maxY=Math.max(600,...cs.map(c=>c.y+c.h))+25;
 const textLines=(text,x,y,width,ink)=>{const words=String(text).split(/\s+/),lines=[];let line='';for(const word of words){if((line+' '+word).length>Math.max(15,Math.floor(width/7))){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);return lines.map((l,i)=>`<text x="${x}" y="${y+i*19}" fill="${ink||'#3f3f46'}" font-size="12">${esc(l)}</text>`).join('');};
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minX} ${minY} ${maxX-minX} ${maxY-minY}"><style>text{font-family:Arial,sans-serif}</style><rect x="${minX}" y="${minY}" width="100%" height="100%" fill="#f6f6f4"/>`+b.edges.filter(e=>cs.some(c=>c.id===e.from)&&cs.some(c=>c.id===e.to)).map(e=>{const f=cs.find(c=>c.id===e.from),t=cs.find(c=>c.id===e.to);return `<path d="M${f.x+f.w} ${f.y+f.h/2}L${t.x} ${t.y+t.h/2}" fill="none" stroke="#8a8a90"/><text x="${(f.x+f.w+t.x)/2}" y="${(f.y+f.h/2+t.y+t.h/2)/2-8}" fill="#6b6b72" font-size="10">${esc(e.label)}</text>`;}).join('')+linkPaths(b)+[...cs].sort((a,b)=>(C.container(a)?-1:0)-(C.container(b)?-1:0)).map(c=>`<g><rect x="${c.x}" y="${c.y}" width="${c.w}" height="${c.h}" rx="6" fill="${c.style?.fill||colors[c.color]||'#fff'}" stroke="#e4e4e0"/><clipPath id="clip-${c.id}"><rect x="${c.x+2}" y="${c.y+2}" width="${c.w-4}" height="${c.h-4}"/></clipPath><g clip-path="url(#clip-${c.id})">${['image','sketch'].includes(c.type)&&c.media?`<image href="${esc(c.media)}" x="${c.x}" y="${c.y+40}" width="${c.w}" height="${c.h-40}" preserveAspectRatio="xMidYMid meet"/>`:''}<text x="${c.x+18}" y="${c.y+29}" font-size="${c.type==='heading'?20:14}" font-weight="bold" fill="${c.style?.ink||'#18181b'}">${esc(c.title)}</text>${c.type==='timeline'?timelineSvg(c,b):textLines(c.type==='task'?c.items.map(i=>(i.done?'✓ ':'□ ')+i.text).join(' / '):c.type==='board'?'Nested board: '+workspace.boards.find(b=>b.id===c.boardId)?.name:(c.type==='table'?c.cells.map(row=>row.join(' | ')).join(' / '):c.body)+(c.url?' '+c.url:''),c.x+18,c.y+58,c.w-36,c.style?.ink)}</g></g>`).join('')+'</svg>';
}
function showExport(){modal('Take your ideas with you.','Portable files. No account required.',`<div class="export-options"><button class="export-option" data-export="json">${icon('board')}<span><strong>Workspace backup · JSON</strong><small>All boards, embedded files, and annotations. Managed originals and large videos stay on this Mac; copy them separately when migrating.</small></span></button><button class="export-option" data-export="svg">${icon('image')}<span><strong>Current board · SVG</strong><small>A scalable visual snapshot of cards and connections.</small></span></button><button class="export-option" data-export="md">${icon('note')}<span><strong>Current board · Markdown</strong><small>Notes, links, tags, and checklists as plain text.</small></span></button><button class="export-option" id="import-backup">${icon('download')}<span><strong>Import workspace backup</strong><small>Replaces this workspace. Export your current work first.</small></span></button></div>`);$('#modal').querySelectorAll('[data-export]').forEach(btn=>btn.onclick=async()=>{const type=btn.dataset.export,b=current(),name=(type==='json'?'atelier-workspace':b.name.replace(/[^a-z0-9_-]/gi,'-'))+'.'+type;try{const ok=await storage.exportFile(name,type==='json'?JSON.stringify(workspace,null,2):type==='md'?markdown(b):svgExport(b),type==='json'?'application/json':type==='svg'?'image/svg+xml':'text/markdown');if(ok)toast('Export saved.');}catch(e){toast(e.message||e);}});$('#import-backup').onclick=()=>{$('#modal').close();$('#import-input').click();};}
async function importBackup(file){if(!file)return;if(file.size>100*1024*1024){toast('Backup exceeds 100 MB.');return;}try{const incoming=validate(JSON.parse(await file.text()));modal('Replace the current workspace?','Export a backup first if you want to keep a separate copy. This action can also be undone.',`<p>${incoming.boards.length} boards ready to import.</p><div class="modal-footer"><button class="button primary" id="confirm-import">Import workspace</button></div>`);$('#confirm-import').onclick=()=>{$('#modal').close();loadFailed=false;change(()=>{workspace=incoming;selected.clear();});toast('Workspace imported.');};}catch(e){toast('Could not import: '+e.message);}}
async function addFiles(files,point,startIndex=0,onto=null){
 const input=$('#media-input'),replace=input.dataset.replace;delete input.dataset.replace;delete input.dataset.type;const added=[];
 const modelFiles=files.filter(f=>isModel(f.name)),resources=[];if(modelFiles.length){if(files.length>100)throw Error('Select at most 100 model resources.');for(const f of files.filter(f=>/\.(mtl|bin|png|jpe?g|webp|gif)$/i.test(f.name))){if(f.size>15*1024*1024)throw Error(f.name+' exceeds 15 MB.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(f);});resources.push({name:f.webkitRelativePath||f.name,data:data.replace(/^data:[^;]*;/,'data:application/octet-stream;')});}files=files.filter(f=>isModel(f.name)||!resources.some(a=>a.name===(f.webkitRelativePath||f.name))); }
 for(const f of files){if(f.size>(isModel(f.name)?50:15)*1024*1024){toast(`${f.name} exceeds the ${isModel(f.name)?50:15} MB limit.`);continue;}let type=isModel(f.name)?'model':f.type.startsWith('image/')?'image':f.type.startsWith('video/')?'video':'file';let media=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(f);});
 if(!/^data:(image\/(png|jpeg|webp|gif)|video\/(mp4|webm|ogg|quicktime|x-msvideo|x-matroska)|application\/pdf|text\/plain);base64,/.test(media)){if(type!=='file'&&type!=='model'){toast('Unsupported media type: '+f.name);continue;}media=media.replace(/^data:[^;]*;/,'data:application/octet-stream;');}
 const c=replace?clone(current().cards.find(c=>c.id===replace)):card(type,(point?.x??100)+((added.length+startIndex)%3)*280,(point?.y??100)+Math.floor((added.length+startIndex)/3)*250);if(!c)continue;c.type=type;c.media=media;c.filename=f.name;delete c.localVideo;delete c.localAttachment;delete c.preview;delete c.modelView;delete c.assets;if(f.nativeId)c.localAttachment=f.nativeId;if(type==='model'){c.assets=resources;c.w=300;c.h=220;}c.title=f.name.replace(/\.[^.]+$/,'');if(type==='image'){const img=new Image();img.src=media;try{await img.decode();c.h=Math.min(500,Math.max(180,c.w*img.height/img.width+40));}catch{if(c.localAttachment){c.type='file';c.media='';c.body='Original file preserved. Image preview could not be decoded.';}else{toast('Image could not be decoded.');continue;}}}added.push(c);if(replace)break;
 }
 if(added.length){const candidate=clone(workspace),b=candidate.boards.find(b=>b.id===candidate.active);if(replace)b.cards=b.cards.map(c=>c.id===replace?added[0]:c);else b.cards.push(...added);if(new TextEncoder().encode(JSON.stringify(candidate)).length>100*1024*1024){toast('Adding these files would exceed the 100 MB workspace limit.');return;}const host=onto&&!replace&&b.cards.find(c=>c.id===onto.c.id&&c.type==='timeline');let made=[];change(()=>{workspace=candidate;selected=new Set(added.map(c=>c.id));if(host)made=attachItems(host,added,onto.at,onto.lane);});if(made.length)connected(host,made,added);else toast(added.length===1?'Reference added.':`${added.length} references added.`);}
 input.value='';
}
function sketch(existing){const root=modal('Sketch','Choose a palette, draw, and label your ideas. Changing Paper fills the canvas; Undo restores it.','');drawing(root,existing,data=>{$('#modal').close();change(()=>{const c=existing||card('sketch',100,100);c.media=data;c.w=350;c.h=265;if(!existing)current().cards.push(c);selected=new Set([c.id]);});});}
async function settings(){const rs=await storage.revisions();modal('Your space. Your rules.','Small adjustments for the way you work.',`<div class="field"><label for="setting-name">Name for annotations</label><input id="setting-name" value="${esc(localStorage.getItem('atelier-name')||'You')}"></div><div class="field"><label><input id="dark-setting" type="checkbox" ${document.body.classList.contains('dark')?'checked':''} style="width:auto"> Dark workspace</label><label><input id="snap-setting" type="checkbox" ${localStorage.getItem('atelier-snap')==='yes'?'checked':''} style="width:auto"> Snap cards to grid</label></div><p class="inline-note">${storage.isNative()?'Desktop edition · Rust + SQLite. Recovery snapshots are retained automatically.':'Browser preview · IndexedDB. Desktop edition uses Rust + SQLite.'}</p>${rs.length?'<div class="label">Recovery snapshots</div>'+rs.map(r=>`<button class="export-option" data-revision="${r.id}" style="width:100%;margin-top:8px">${icon('undo')} ${esc(r.created)} UTC</button>`).join(''):''}<div class="modal-footer"><button id="save-settings" class="button primary">Save preferences</button></div>`);$('#save-settings').onclick=()=>{localStorage.setItem('atelier-name',$('#setting-name').value||'You');localStorage.setItem('atelier-dark',$('#dark-setting').checked?'yes':'no');localStorage.setItem('atelier-snap',$('#snap-setting').checked?'yes':'no');document.body.classList.toggle('dark',$('#dark-setting').checked);$('#modal').close();};$('#modal').querySelectorAll('[data-revision]').forEach(btn=>btn.onclick=async()=>{try{const restored=validate(JSON.parse(await storage.restoreRevision(Number(btn.dataset.revision))));modal('Restore this snapshot?','Current changes will be replaced. You can undo the restore.',`<div class="modal-footer"><button class="button primary" id="restore-confirm">Restore</button></div>`);$('#restore-confirm').onclick=()=>{$('#modal').close();change(()=>{workspace=restored;selected.clear();});};}catch(e){toast(e.message||e);}});}
function help(){modal('Keep the flow.','Keyboard shortcuts',`<div class="shortcuts">${[['New note','N'],['New checklist','T'],['New link','L'],['Connect cards','C'],['Search workspace','⌘ / Ctrl K'],['Undo / redo','⌘ Z / ⌘ ⇧ Z'],['Select all cards','⌘ / Ctrl A'],['Duplicate selected','⌘ / Ctrl D'],['Copy / paste selected','⌘ C / ⌘ V'],['Delete selected','Backspace / Delete'],['Select several cards','Shift + click / drag empty canvas'],['Group / ungroup','⌘ / Ctrl G / ⇧ G'],['Organize objects','Right-click selection'],['Present frames','Present / ← / → / Esc'],['Pan canvas','Space + drag / middle drag'],['Zoom canvas','Ctrl + scroll'],['Fit board','F'],['Connect a card to a timeline','Drag it onto the timeline'],['Nudge a timeline clip','← / → (Shift for a second or a week)'],['Disconnect a timeline clip','Backspace / Delete'],['Edit card','Double-click / Enter'],['Clear selection','Escape']].map(([a,b])=>`<span>${a}</span><kbd>${b}</kbd>`).join('')}</div><p class="inline-note" style="margin-top:25px">Atelier is a standalone local workspace. Cloud sync, real-time collaboration, web clipping, and online previews are not included in this release.</p>`);}
function undo(){if(!history.past.length)return;workspace=history.undo(workspace);selected.clear();dirty();render();}
function redo(){if(!history.future.length)return;workspace=history.redo(workspace);selected.clear();dirty();render();}
function bind(){
 hydrate();renderTools();$('#new-board').onclick=()=>newBoard();$('#templates-open').onclick=showTemplates;$('#search-open').onclick=showSearch;$('#board-title').ondblclick=$('#board-description').ondblclick=renameBoard;$('#board-menu').onclick=boardMenu;$('#undo').onclick=undo;$('#redo').onclick=redo;$('#export-open').onclick=showExport;$('#settings-open').onclick=()=>settings().catch(e=>toast(e.message));$('#help-open').onclick=help;$('#first-note').onclick=()=>add('note');$('#zoom-in').onclick=()=>zoom(current().view.zoom+.1);$('#zoom-out').onclick=()=>zoom(current().view.zoom-.1);$('#zoom-label').onclick=()=>zoom(1);$('#fit').onclick=fit;
 $('#media-input').onchange=e=>addFiles([...e.target.files]).catch(e=>toast(e.message));$('#import-input').onchange=e=>{importBackup(e.target.files[0]);e.target.value='';};
 const canvas=$('#canvas');canvas.ondblclick=e=>{if(e.target===canvas||e.target.id==='world'||e.target.id==='cards')add('note',position(e));};
 canvas.addEventListener('pointerdown',e=>{if(e.button===1||space){e.preventDefault();const start={x:e.clientX,y:e.clientY},v=current().view,before={x:v.x,y:v.y};canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';const move=ev=>{v.x=before.x+ev.clientX-start.x;v.y=before.y+ev.clientY-start.y;view();};const end=()=>{canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',end);canvas.removeEventListener('pointercancel',end);canvas.style.cursor='';dirty();};canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);}else if(!e.target.closest('.card,button,input,select,#tools,.canvas-bottom,.canvas-navigation,#canvas-outline,#canvas-minimap')){selected.clear();activeItem=null;renderCards();renderInspector();}});
 canvas.addEventListener('wheel',e=>{e.preventDefault();if(e.ctrlKey||e.metaKey){const r=canvas.getBoundingClientRect();zoom(current().view.zoom*Math.exp(-e.deltaY*.003),e.clientX-r.left,e.clientY-r.top);}else{current().view.x-=e.deltaX;current().view.y-=e.deltaY;view();dirty();}},{passive:false});
 canvas.ondragover=e=>{e.preventDefault();canvas.classList.add('drop-active');e.dataTransfer.dropEffect='copy';dropHint(timelineAt(e.clientX,e.clientY));};canvas.ondragleave=e=>{if(!canvas.contains(e.relatedTarget)){canvas.classList.remove('drop-active');dropHint(null);}};canvas.ondrop=e=>{e.preventDefault();canvas.classList.remove('drop-active');const hit=timelineAt(e.clientX,e.clientY),point=hit?beneath(hit,e):position(e);dropHint(null);if(e.dataTransfer.files.length)addFiles([...e.dataTransfer.files],point,0,hit).catch(e=>toast(e.message));else{const text=e.dataTransfer.getData('text/uri-list')||e.dataTransfer.getData('text/plain');if(text){const c=card(/^https?:\/\//.test(text)?'link':'note',point.x,point.y);if(c.type==='link'){c.url=text;c.title='Saved link';}else c.body=text;let made=[];change(()=>{current().cards.push(c);selected=new Set([c.id]);if(hit)made=attachItems(hit.c,[c],hit.at,hit.lane);});if(made.length)connected(hit.c,made,[c]);}}};
 document.addEventListener('keydown',e=>{
  const editing=e.target.closest('input,textarea,select,[contenteditable]');if($('#modal').open)return;
  if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showSearch();return;}if(editing)return;
  if(e.code==='Space'){e.preventDefault();space=true;canvas.style.cursor='grab';return;}
  const cmd=e.metaKey||e.ctrlKey,k=e.key.toLowerCase(),entry=!cmd&&activeEntry(),clip=entry&&!C.locked(current(),entry.c)?entry:null;
  if(clip&&(e.key==='Backspace'||e.key==='Delete')){e.preventDefault();change(()=>{clip.c.timeline.items=clip.c.timeline.items.filter(i=>i!==clip.item);activeItem=null;});return;}
  if(clip&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();const tl=clip.c.timeline,step=(e.shiftKey?(tl.mode==='date'?7:T.base(tl)):1)*(e.key==='ArrowLeft'?-1:1);if(Date.now()-nudged>900)history.push(workspace);nudged=Date.now();clip.item.at=tl.mode==='date'?clip.item.at+step:T.fromNominal(Math.max(0,T.toNominal(clip.item.at,tl)+step),tl);T.place(tl,clip.item);dirty();render();return;}
  if(cmd&&k==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(cmd&&k==='y'){e.preventDefault();redo();}else if(cmd&&k==='a'){e.preventDefault();selected=new Set(current().cards.filter(c=>C.visible(current(),c)&&!C.locked(current(),c)).map(c=>c.id));renderCards();renderInspector();}else if(cmd&&k==='d'){e.preventDefault();change(()=>selected=new Set(duplicateCards(current(),selected)));}else if(cmd&&k==='c'){e.preventDefault();clipboard=clone(current().cards.filter(c=>selected.has(c.id)));toast(`${clipboard.length} cards copied.`);}else if(cmd&&k==='v'&&clipboard.length){e.preventDefault();change(()=>{const map=new Map(),copies=clone(clipboard).map(c=>{const id=uid();map.set(c.id,id);return {...c,id,x:c.x+40,y:c.y+40};});C.remap(copies,map,uid);copies.forEach(c=>{if(c.layerId&&!current().layers?.some(l=>l.id===c.layerId))delete c.layerId;if(c.sectionId&&!current().cards.some(x=>x.id===c.sectionId)&&!copies.some(x=>x.id===c.sectionId))delete c.sectionId;if(c.timeline)T.recopy(c.timeline,uid,map);});current().cards.push(...copies);T.prune(current().cards);selected=new Set(copies.map(c=>c.id));});}else if(cmd&&k==='s'){e.preventDefault();persist();}else if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();deleteSelected();}else if(e.key==='Escape'){selected.clear();activeItem=null;connectMode=false;connectFrom=null;render();renderTools();}else if(e.key==='Enter'&&selected.size){renderInspector();$('#edit-title')?.focus();}else if(!cmd){if(k==='n')add('note');if(k==='t')add('task');if(k==='l')add('link');if(k==='f')fit();if(k==='c'){connectMode=!connectMode;connectFrom=null;renderTools();}}
 });document.addEventListener('keyup',e=>{if(e.code==='Space'){space=false;canvas.style.cursor='';}});window.addEventListener('blur',()=>{space=false;canvas.style.cursor='';});
 document.addEventListener('paste',e=>{if(e.target.closest('input,textarea')||$('#modal').open)return;const files=[...e.clipboardData.files];if(files.length){e.preventDefault();addFiles(files).catch(e=>toast(e.message));}});
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){clearTimeout(saveTimer);persist();}});
}
try{workspace=await storage.load()||initial();}catch(e){workspace=initial();loadFailed=true;setTimeout(()=>{toast('Saved workspace could not be loaded. Your saved data has been preserved.');modal('Your saved work needs attention.','Automatic saving is paused to preserve the existing workspace.',`<p class="inline-note">${esc(e.message||e)}. Import a valid backup to recover, or explicitly start a new workspace.</p><div class="modal-footer"><button class="button" id="recover-import">Import backup</button><button class="button danger" id="recover-new">Start new workspace</button></div>`);$('#recover-import').onclick=()=>{$('#modal').close();$('#import-input').click();};$('#recover-new').onclick=()=>{$('#modal').close();loadFailed=false;persist();};},100);}
canvasUX=createCanvasUX({board:current,selected:()=>selected,select:s=>{selected=s;activeItem=null;},change,render,view,dirty,focus:focusCard,toast,position,space:()=>space,mark:markSelection,duplicate:()=>change(()=>selected=new Set(duplicateCards(current(),selected))),remove:deleteSelected});
document.body.classList.toggle('dark',localStorage.getItem('atelier-dark')==='yes');bind();render();if(!loadFailed)persist();

if(storage.isNative()){const win=window.__TAURI__.window.getCurrentWindow();let closing=false;win.onCloseRequested(async event=>{event.preventDefault();if(closing)return;closing=true;await viewerCleanup?.();viewerCleanup=null;clearTimeout(saveTimer);if(loadFailed||await persist())await win.destroy();else closing=false;}).catch(e=>toast('Close protection unavailable: '+String(e)));}

// Finder drops are intercepted by Tauri, so the browser File API is insufficient.
if(storage.isNative()&&window.__TAURI__.webview){let importing=false;const canvas=$('#canvas');window.__TAURI__.webview.getCurrentWebview().onDragDropEvent(async({payload})=>{
 const p=payload.position?{clientX:payload.position.x/devicePixelRatio,clientY:payload.position.y/devicePixelRatio}:null,r=canvas.getBoundingClientRect();const inside=p&&p.clientX>=r.left&&p.clientX<=r.right&&p.clientY>=r.top&&p.clientY<=r.bottom&&!$('#modal').open;
 const hovering=!!inside&&['enter','over'].includes(payload.type);canvas.classList.toggle('drop-active',hovering);dropHint(hovering?timelineAt(p.clientX,p.clientY):null);
 if(payload.type!=='drop'||!inside)return;if(importing){toast('Please wait for the current import.');return;}importing=true;const target=current().id,hit=timelineAt(p.clientX,p.clientY),point=hit?beneath(hit,p):position(p),host=()=>hit&&current().cards.find(c=>c.id===hit.c.id&&c.type==='timeline');toast('Importing dropped files…');
 try{const result=await window.__TAURI__.core.invoke('import_dropped_files',{paths:payload.paths});if(current().id!==target){toast('Import cancelled because the active board changed. Drop the files again.');return;}
 const files=[],managed=[];for(const item of result.files){if(item.kind==='video'||!item.data){const c=card(item.kind==='video'?'video':'file',point.x+(managed.length%3)*280,point.y+Math.floor(managed.length/3)*250);c.localAttachment=item.id;if(item.kind==='video')c.localVideo=item.id;c.title=item.filename;c.filename=item.filename;c.body=item.kind!=='video'?'Original file preserved. In-app viewer unavailable.':'';managed.push(c);}else{const blob=await(await fetch(item.data)).blob(),f=new File([blob],item.filename,{type:blob.type});f.nativeId=item.id;files.push(f);}}
 if(files.length)await addFiles(files,point,managed.length,hit);if(managed.length)change(()=>{current().cards.push(...managed);selected=new Set(managed.map(c=>c.id));const tl=host();if(tl)attachItems(tl,managed,hit.at,hit.lane);});if(result.errors.length)toast(result.errors.join(' · '));else toast(`${result.files.length} files imported.`);
 }catch(e){toast(String(e));}finally{importing=false;canvas.classList.remove('drop-active');dropHint(null);}
 }).catch(e=>toast('Finder drop handler unavailable: '+String(e)));}
