import {isModel,openViewer} from './viewer.js';
import {uid,clone,card,board,History,validate,removeCards,duplicateCards,markdown,templates,applyTemplate,initial} from './model.js';
import {icon,hydrate} from './icons.js';
import * as storage from './storage.js';
import {renderMarkdown} from './format.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const history=new History();let workspace,selected=new Set(),connectMode=false,connectFrom=null,space=false,saveTimer,toastTimer,clipboard=[],saveChain=Promise.resolve(),loadFailed=false;
const colors={paper:'#ffffff',sage:'#e8efdf',sand:'#f6efd9',rose:'#f4e5df',sky:'#e5edf0',stone:'#eeefe9'};
const current=()=>workspace.boards.find(b=>b.id===workspace.active);
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function dirty(){current().updated=Date.now();$('#save-status').innerHTML='<i></i> Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(persist,400);}
function persist(){
 if(loadFailed)return;
 const snapshot=clone(workspace);saveChain=saveChain.catch(()=>{}).then(()=>storage.save(snapshot)).then(()=>{$('#save-status').innerHTML='<i></i> Saved locally';return true;}).catch(e=>{$('#save-status').textContent='Save failed';toast(e.message||String(e));return false;});return saveChain;
}
function change(fn){history.push(workspace);fn();dirty();render();}
function navigate(id){if(!workspace.boards.some(b=>b.id===id))return;workspace.active=id;selected.clear();connectFrom=null;dirty();render();}
function ancestors(b){const list=[];while(b){list.unshift(b);b=workspace.boards.find(x=>x.id===b.parent);}return list;}
function render(){renderSidebar();renderBoard();renderCards();renderInspector();$('#undo').disabled=!history.past.length;$('#redo').disabled=!history.future.length;}
function renderSidebar(){
 const rows=[];function tree(parent,depth=0){workspace.boards.filter(b=>b.parent===parent).forEach(b=>{rows.push(`<button class="board-row ${depth?'child':''} ${b.id===workspace.active?'active':''}" data-board="${b.id}" style="padding-left:${12+Math.min(depth,5)*16}px">${icon('board')}<span class="name">${esc(b.name)}</span><span class="count">${b.cards.length}</span></button>`);tree(b.id,depth+1);});}tree(null);
 $('#boards').innerHTML=rows.join('');$('#boards').querySelectorAll('[data-board]').forEach(el=>el.onclick=()=>navigate(el.dataset.board));
}
function renderBoard(){const b=current();$('#board-title').textContent=b.name;$('#board-description').textContent=b.description;$('#breadcrumbs').innerHTML=`${icon('home')}<span>/</span>`+ancestors(b).map((a,i,arr)=>`<button data-nav="${a.id}" class="${i===arr.length-1?'current':''}">${esc(a.name)}</button>`).join('<span>/</span>');$('#breadcrumbs').querySelectorAll('[data-nav]').forEach(el=>el.onclick=()=>navigate(el.dataset.nav));view();$('#empty').style.display=b.cards.length?'none':'block';}
function view(){const v=current().view;$('#world').style.transform=`translate(${v.x}px,${v.y}px) scale(${v.zoom})`;$('#zoom-label').textContent=Math.round(v.zoom*100)+'%';$('#canvas').style.backgroundPosition=`${v.x}px ${v.y}px`;$('#canvas').style.backgroundSize=`${22*v.zoom}px ${22*v.zoom}px`;}
function media(c){if(!c.media)return `<div class="card-body">Drop a file here, or use the inspector to upload.</div>`;if(c.type==='video')return `<video class="card-media" controls preload="metadata" src="${esc(c.media)}"></video>`;return `<img class="card-media" alt="${esc(c.title)}" src="${esc(c.media)}" draggable="false">`;}
function renderCards(){
 const b=current();$('#cards').innerHTML=b.cards.map(c=>{
 let content='';
 if(c.type==='task'){const done=c.items.filter(i=>i.done).length;content=`<div class="task-list">${c.items.map(i=>`<label class="task-item ${i.done?'done':''}"><input type="checkbox" data-task="${i.id}" ${i.done?'checked':''}><span>${esc(i.text)}</span></label>`).join('')}</div><div class="progress-track"><i style="width:${c.items.length?done/c.items.length*100:0}%"></i></div>`;}
 else if(['image','video','sketch'].includes(c.type))content=media(c);
 else if(c.type==='board'){const sub=workspace.boards.find(x=>x.id===c.boardId);content=`<div class="board-cover" data-enter="${c.boardId}">${icon('board')}</div><div class="board-sub">${sub?.cards.length||0} ideas inside ${icon('arrow')}</div>`;}
 else if(c.type==='link'){let domain='Add a website address';try{domain=new URL(c.url).hostname;}catch{}content=`<div class="card-body"><span class="link-domain">${esc(domain)}</span>${esc(c.body)}<br>${c.url?'<button class="open-link">Open link ↗</button>':''}</div>`;}
 else if(c.type==='model')content=`${c.preview?`<img class="model-preview" alt="${esc(c.title)}" src="${esc(c.preview)}">`:''}<div class="card-body">${esc(c.filename)}<br><button class="open-model button">Explore in 3D</button></div>`;
 else if(c.type==='file')content=`<div class="card-body">${esc(c.filename||'No file attached')}<br>${esc(c.body)}${c.media?'<br><button class="open-link download-attachment">Save attachment ↓</button>':''}</div>`;
 else content=`<div class="card-body ${c.type==='note'?'note-text':''}">${c.type==='note'?renderMarkdown(c.body):esc(c.body)}</div>`;
 const footer=c.tags.length||c.comments.length?`<div class="card-footer">${c.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}${c.comments.length?`<span class="comment-count">${c.comments.length} ${icon('comment')}</span>`:''}</div>`:'';
 return `<article class="card ${c.type} color-${Object.keys(colors).includes(c.color)?c.color:'paper'} ${selected.has(c.id)?'selected':''}" data-id="${c.id}" style="left:${c.x}px;top:${c.y}px;width:${c.w}px;height:${c.h}px"><div class="card-header"><span class="card-type">${icon(c.type)}</span><span class="card-title">${esc(c.type==='board'?workspace.boards.find(b=>b.id===c.boardId)?.name:c.title)}</span><button class="card-more" title="Edit card" aria-label="Edit ${esc(c.title)}">${icon('more')}</button></div>${content}${footer}<div class="resize-handle"></div></article>`;
 }).join('');
 $('#cards').querySelectorAll('.card').forEach(el=>{
 const c=b.cards.find(c=>c.id===el.dataset.id);
 el.addEventListener('pointerdown',e=>cardPointer(e,c,el));
 el.ondblclick=e=>{if(e.target.closest('input,video,button'))return;if(c.type==='board')navigate(c.boardId);else if(c.type==='model')showModel(c);else{selected=new Set([c.id]);renderInspector();}};
 el.querySelector('.card-more').onclick=e=>{e.stopPropagation();selected=new Set([c.id]);renderCards();renderInspector();};
 el.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>change(()=>c.items.find(i=>i.id===x.dataset.task).done=x.checked));
 if(c.type==='board')el.querySelector('[data-enter]').onclick=()=>navigate(c.boardId);
 if(c.type==='link')el.querySelector('.open-link')?.addEventListener('click',()=>{try{Promise.resolve(storage.openLink(c.url)).catch(e=>toast(e.message||e));}catch(e){toast(e.message);}});
 if(c.type==='model')el.querySelector('.open-model').onclick=()=>showModel(c);
 if(c.type==='file')el.querySelector('.download-attachment')?.addEventListener('click',()=>{storage.saveAttachment(c.filename||'attachment',c.media).then(ok=>{if(ok)toast('Attachment saved.');}).catch(e=>toast(e.message||e));});
 });renderEdges();
}
function renderEdges(){const b=current();$('#edges').innerHTML=`<defs><marker id="arrowhead" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0l10 5-10 5" fill="#a3b094"/></marker></defs>`+b.edges.map(e=>{const f=b.cards.find(c=>c.id===e.from),t=b.cards.find(c=>c.id===e.to);if(!f||!t)return '';const right=t.x>=f.x,x1=f.x+(right?f.w:0),y1=f.y+f.h/2,x2=t.x+(right?0:t.w),y2=t.y+t.h/2,d=Math.max(60,Math.abs(x2-x1)/2)*(right?1:-1);return `<g data-edge="${e.id}"><path class="edge-path" marker-end="url(#arrowhead)" d="M${x1} ${y1}C${x1+d} ${y1} ${x2-d} ${y2} ${x2} ${y2}"/><text class="edge-label" x="${(x1+x2)/2}" y="${(y1+y2)/2-10}" text-anchor="middle">${esc(e.label)}</text></g>`;}).join('');$('#edges').querySelectorAll('[data-edge]').forEach(el=>el.ondblclick=()=>editEdge(el.dataset.edge));}
function position(e){const r=$('#canvas').getBoundingClientRect(),v=current().view;return {x:(e.clientX-r.left-v.x)/v.zoom,y:(e.clientY-r.top-v.y)/v.zoom};}
function cardPointer(e,c,el){
 if(e.button!==0||e.target.closest('button,input,video,a')||space)return;
 if(connectMode){e.preventDefault();if(!connectFrom){connectFrom=c.id;toast('Select another card to connect.');}else if(connectFrom!==c.id){change(()=>current().edges.push({id:uid(),from:connectFrom,to:c.id,label:''}));connectFrom=null;connectMode=false;renderTools();toast('Connected. Double-click the line to label it.');}return;}
 if(e.shiftKey){selected.has(c.id)?selected.delete(c.id):selected.add(c.id);renderCards();renderInspector();return;}
 if(!selected.has(c.id)){selected=new Set([c.id]);$('#cards').querySelectorAll('.card').forEach(x=>x.classList.toggle('selected',selected.has(x.dataset.id)));renderInspector();}
 const resize=e.target.closest('.resize-handle');
 if(!resize&&!e.target.closest('.card-header')&&c.type!=='column')return;
 e.preventDefault();e.stopPropagation();const start={x:e.clientX,y:e.clientY},before=clone(workspace),original=current().cards.filter(x=>selected.has(x.id)||(!resize&&current().cards.some(g=>selected.has(g.id)&&g.type==='column'&&x.type!=='column'&&x.x>=g.x&&x.y>=g.y&&x.x+x.w<=g.x+g.w&&x.y+x.h<=g.y+g.h))).map(x=>({id:x.id,x:x.x,y:x.y,w:x.w,h:x.h}));let moved=false;
 el.setPointerCapture(e.pointerId);
 const move=ev=>{const dx=(ev.clientX-start.x)/current().view.zoom,dy=(ev.clientY-start.y)/current().view.zoom;if(Math.abs(dx)+Math.abs(dy)<3&&!moved)return;moved=true;for(const o of original){const target=current().cards.find(x=>x.id===o.id);if(resize){target.w=Math.max(140,Math.min(3000,o.w+dx));target.h=Math.max(65,Math.min(3000,o.h+dy));}else{target.x=Math.max(-90000,Math.min(90000,o.x+dx));target.y=Math.max(-90000,Math.min(90000,o.y+dy));}const node=$(`[data-id="${o.id}"]`);node.style.left=target.x+'px';node.style.top=target.y+'px';node.style.width=target.w+'px';node.style.height=target.h+'px';}renderEdges();};
 const end=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',end);if(moved){history.push(before);if($('#snap-setting')?.checked||localStorage.getItem('atelier-snap')==='yes')for(const o of original){const t=current().cards.find(x=>x.id===o.id);t.x=Math.round(t.x/22)*22;t.y=Math.round(t.y/22)*22;}dirty();render();}};
 el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);
}
function add(type,point){if(type==='model'){$('#media-input').click();return;}if(type==='image'||type==='video'||type==='file'){$('#media-input').dataset.type=type;$('#media-input').click();return;}if(type==='sketch'){sketch();return;}if(type==='board'){newBoard(true);return;}
 const p=point||{x:(180-current().view.x)/current().view.zoom,y:(100-current().view.y)/current().view.zoom};change(()=>{const c=card(type,p.x,p.y);current().cards.push(c);selected=new Set([c.id]);});}
function renderTools(){const names={note:'Note · N',task:'To-do list · T',image:'Image',link:'Link · L',board:'Nested board',column:'Column',heading:'Heading',sketch:'Sketch',file:'File or video',model:'3D model + resources',connect:'Connect ideas · C'};$('#tools').innerHTML=Object.entries(names).map(([type,label],i)=>`${i===9?'<div class="tool-separator"></div>':''}<button class="tool ${type==='connect'&&connectMode?'active':''}" data-type="${type}" data-label="${label}" title="${label}" aria-label="${label}">${icon(type)}</button>`).join('');$('#tools').querySelectorAll('[data-type]').forEach(el=>el.onclick=()=>{if(el.dataset.type==='connect'){connectMode=!connectMode;connectFrom=null;renderTools();if(connectMode)toast('Click the first card, then the second.');}else add(el.dataset.type);});}
function editField(c,key,value){history.push(workspace);c[key]=value;dirty();renderCards();renderSidebar();$('#undo').disabled=false;}
function renderInspector(){
 const el=$('#inspector'),cards=current().cards.filter(c=>selected.has(c.id));el.classList.toggle('hidden',!cards.length);if(!cards.length)return;
 const close=`<button class="icon-button" id="inspector-close" aria-label="Close inspector">${icon('close')}</button>`;
 if(cards.length>1){el.innerHTML=`<div class="inspector-head"><span>SELECTION</span>${close}</div><div class="selection-info">${cards.length} ideas selected</div><div class="select-actions"><button class="button" id="align-left">Align left</button><button class="button" id="align-top">Align top</button><button class="button" id="arrange">Arrange in a grid</button><button class="button" id="duplicate">Duplicate</button><button class="button danger" id="delete-card">Delete selected</button></div>`;$('#align-left').onclick=()=>change(()=>cards.forEach(c=>c.x=Math.min(...cards.map(c=>c.x))));$('#align-top').onclick=()=>change(()=>cards.forEach(c=>c.y=Math.min(...cards.map(c=>c.y))));$('#arrange').onclick=()=>arrange(cards);}
 else{
 const c=cards[0];el.innerHTML=`<div class="inspector-head"><span>${esc(c.type.toUpperCase())} / DETAILS</span>${close}</div><div class="field"><label for="edit-title">Title</label><input id="edit-title" maxlength="1000" value="${esc(c.type==='board'?workspace.boards.find(x=>x.id===c.boardId)?.name:c.title)}"></div>${!['image','video','sketch','board','task'].includes(c.type)?`<div class="field"><label for="edit-body">${c.type==='heading'?'Subtitle':'Notes'}</label>${c.type==='note'?'<div class="format-tools"><button data-format="bold" title="Bold"><strong>B</strong></button><button data-format="italic" title="Italic"><em>I</em></button><button data-format="list" title="Bulleted list">• List</button><button data-format="heading" title="Heading">H</button></div>':''}<textarea id="edit-body">${esc(c.body)}</textarea></div>`:''}
 ${c.type==='link'?`<div class="field"><label for="edit-url">Website address</label><input id="edit-url" placeholder="https://…" value="${esc(c.url)}"></div>`:''}
 ${c.type==='task'?`<div class="label">Checklist</div><div id="task-editor">${c.items.map(i=>`<div class="task-edit" data-item="${i.id}"><input type="checkbox" ${i.done?'checked':''} aria-label="Complete task"><input class="text-input" value="${esc(i.text)}" aria-label="Task text"><button aria-label="Remove task">${icon('close')}</button></div>`).join('')}</div><button id="add-task" class="button">${icon('plus')} Add task</button><br><br>`:''}
 ${['image','video','file','sketch'].includes(c.type)?`<button id="replace-media" class="button">${icon(c.type==='sketch'?'pen':'image')} ${c.type==='sketch'?'New sketch':'Replace file'}</button><p class="inline-note">Files are embedded in your workspace. Maximum 15 MB per file.</p>`:''}
 ${c.type==='model'?'<button id="inspect-model" class="button">Explore in 3D</button><p class="inline-note">Import a model together with its MTL and textures. Files stay embedded locally.</p>':''}
 ${c.type==='board'?'<button id="open-sub-board" class="button">Open board →</button><br><br>':''}
 <div class="field"><label>Card color</label><div class="swatches">${Object.entries(colors).map(([key,col])=>`<button class="swatch ${key===c.color?'active':''}" data-color="${key}" style="background:${col}" title="${key}" aria-label="${key}"></button>`).join('')}</div></div>
 <div class="field"><label for="edit-tags">Tags, separated by commas</label><input id="edit-tags" value="${esc(c.tags.join(', '))}" placeholder="inspiration, research"></div>
 <div class="field"><label for="move-board">Move to board</label><select id="move-board">${workspace.boards.map(b=>`<option value="${b.id}" ${b.id===current().id?'selected':''}>${esc(b.name)}</option>`).join('')}</select></div>
 <div class="inspector-actions"><button id="duplicate" class="button">${icon('copy')} Duplicate</button><button id="delete-card" class="button danger">${icon('trash')} Delete</button></div>
 <div class="comments"><div class="label">Personal annotations</div>${c.comments.map((a,i)=>`<div class="comment">${esc(a.text)}<button data-remove-comment="${i}" aria-label="Remove annotation">×</button><small>${esc(a.author)} · ${new Date(a.date).toLocaleDateString()}</small></div>`).join('')}<div class="field"><textarea id="comment-text" placeholder="Leave a thought…" style="min-height:80px" aria-label="Annotation"></textarea></div><button id="add-comment" class="button">Add annotation</button><p class="inline-note">These annotations stay on your device.</p></div>`;
 $('#edit-title').onchange=e=>{const title=e.target.value.trim()||'Untitled';if(c.type==='board')change(()=>{workspace.boards.find(x=>x.id===c.boardId).name=title;c.title=title;});else editField(c,'title',title);};
 if($('#edit-body'))$('#edit-body').onchange=e=>editField(c,'body',e.target.value);
 el.querySelectorAll('[data-format]').forEach(btn=>btn.onclick=()=>{const input=$('#edit-body'),start=input.selectionStart,end=input.selectionEnd,selection=input.value.slice(start,end)||'text',format=btn.dataset.format,insert=format==='bold'?'**'+selection+'**':format==='italic'?'*'+selection+'*':format==='list'?'\n- '+selection:'\n## '+selection;input.setRangeText(insert,start,end,'select');editField(c,'body',input.value);input.focus();});
 if($('#edit-url'))$('#edit-url').onchange=e=>{try{let value=e.target.value;if(value&&!/^https?:\/\//i.test(value))value='https://'+value;if(value&&!['http:','https:'].includes(new URL(value).protocol))throw Error('Use an http or https address.');editField(c,'url',value);e.target.value=value;}catch(e){toast(e.message);}};
 $('#edit-tags').onchange=e=>editField(c,'tags',e.target.value.split(',').map(t=>t.trim()).filter(Boolean).slice(0,20));
 el.querySelectorAll('[data-color]').forEach(btn=>btn.onclick=()=>change(()=>c.color=btn.dataset.color));
 if(c.type==='task'){$('#add-task').onclick=()=>change(()=>c.items.push({id:uid(),text:'New task',done:false}));el.querySelectorAll('[data-item]').forEach(row=>{const i=c.items.find(x=>x.id===row.dataset.item);row.querySelector('[type=checkbox]').onchange=e=>change(()=>i.done=e.target.checked);row.querySelector('.text-input').onchange=e=>{history.push(workspace);i.text=e.target.value;dirty();renderCards();};row.querySelector('button').onclick=()=>change(()=>c.items=c.items.filter(x=>x.id!==i.id));});}
 $('#move-board').onchange=e=>change(()=>{const target=workspace.boards.find(b=>b.id===e.target.value),source=current();source.cards=source.cards.filter(x=>x.id!==c.id);source.edges=source.edges.filter(x=>x.from!==c.id&&x.to!==c.id);target.cards.push(c);selected.clear();});
 $('#add-comment').onclick=()=>{const text=$('#comment-text').value.trim();if(text)change(()=>c.comments.push({author:localStorage.getItem('atelier-name')||'You',text,date:Date.now()}));};el.querySelectorAll('[data-remove-comment]').forEach(btn=>btn.onclick=()=>change(()=>c.comments.splice(Number(btn.dataset.removeComment),1)));
 if($('#replace-media'))$('#replace-media').onclick=()=>{if(c.type==='sketch')sketch(c);else{$('#media-input').dataset.replace=c.id;$('#media-input').dataset.type=c.type;$('#media-input').click();}};
 if($('#inspect-model'))$('#inspect-model').onclick=()=>showModel(c);
 if($('#open-sub-board'))$('#open-sub-board').onclick=()=>navigate(c.boardId);
 }
 $('#inspector-close').onclick=()=>{selected.clear();renderCards();renderInspector();};$('#duplicate').onclick=()=>change(()=>selected=new Set(duplicateCards(current(),selected)));$('#delete-card').onclick=deleteSelected;
}
function deleteSelected(){if(!selected.size)return;change(()=>{removeCards(current(),selected);selected.clear();});}
function arrange(cards=current().cards.filter(c=>c.type!=='heading'&&c.type!=='column')){change(()=>{const w=Math.max(260,...cards.map(c=>c.w))+30,h=Math.max(200,...cards.map(c=>c.h))+30;cards.forEach((c,i)=>{c.x=80+(i%3)*w;c.y=80+Math.floor(i/3)*h;});});}
let viewerCleanup;
function showModel(c){const dialog=modal(c.title,'Drag to orbit · right-drag to pan · scroll to zoom. Select model, MTL and textures together when importing.', '<div id="model-viewer"></div>');dialog.classList.add('model-dialog');viewerCleanup=openViewer($('#model-viewer'),c,(view,preview)=>change(()=>{c.modelView=view;c.preview=preview;}));dialog.addEventListener('close',()=>{viewerCleanup?.();viewerCleanup=null;dialog.classList.remove('model-dialog');},{once:true});}
function modal(title,subtitle,body){viewerCleanup?.();viewerCleanup=null;const el=$('#modal');el.classList.remove('model-dialog');el.innerHTML=`<div class="modal-header"><div><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div><button id="modal-close" class="icon-button" aria-label="Close dialog">${icon('close')}</button></div>${body}`;$('#modal-close').onclick=()=>el.close();if(!el.open)el.showModal();return el;}
function newBoard(nested=false){modal('A space for your next idea.','Give it a name, then make it yours.',`<div class="field"><label for="new-name">Board name</label><input id="new-name" placeholder="Untitled board" maxlength="1000"></div><div class="field"><label for="template-select">Starting point</label><select id="template-select">${templates.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select></div><div class="modal-footer"><button class="button primary" id="create-board">Create board</button></div>`);$('#new-name').focus();$('#create-board').onclick=()=>{const name=$('#new-name').value.trim()||'Untitled board',template=$('#template-select').value;$('#modal').close();change(()=>{const parent=current(),b=applyTemplate(board(name,nested?parent.id:null),template);workspace.boards.push(b);if(nested){const c=card('board',(180-parent.view.x)/parent.view.zoom,(100-parent.view.y)/parent.view.zoom);c.title=name;c.boardId=b.id;parent.cards.push(c);}workspace.active=b.id;selected.clear();});};$('#new-name').onkeydown=e=>{if(e.key==='Enter')$('#create-board').click();};}
function showTemplates(){modal('Begin with a little direction.','Flexible starting points for creative work.',`<div class="template-grid">${templates.map(t=>`<button class="template" data-template="${t.id}">${icon(t.icon)}<strong>${t.name}</strong><p>${t.label}</p></button>`).join('')}</div>`);$('#modal').querySelectorAll('[data-template]').forEach(el=>el.onclick=()=>{const t=templates.find(t=>t.id===el.dataset.template);$('#modal').close();change(()=>{const b=applyTemplate(board(t.id==='blank'?'Untitled board':t.name),t.id);workspace.boards.push(b);workspace.active=b.id;selected.clear();});});}
function renameBoard(){modal('Board details','A title and a little context.',`<div class="field"><label for="rename-title">Title</label><input id="rename-title" maxlength="1000" value="${esc(current().name)}"></div><div class="field"><label for="rename-description">Description</label><textarea id="rename-description">${esc(current().description)}</textarea></div><div class="modal-footer"><button class="button primary" id="rename-save">Save changes</button></div>`);$('#rename-save').onclick=()=>{const name=$('#rename-title').value.trim()||'Untitled board',description=$('#rename-description').value;$('#modal').close();change(()=>{current().name=name;current().description=description;});};}
function boardMenu(){modal('Make this space work for you.','Board tools',`<div class="export-options"><button class="export-option" id="rename-board">${icon('pen')} Rename & describe</button><button class="export-option" id="organize-board">${icon('layout')} Arrange cards in a grid</button><button class="export-option" id="copy-board">${icon('copy')} Duplicate this board</button><button class="export-option" id="clear-edges">${icon('connect')} Remove all connections</button><button class="export-option" id="delete-board">${icon('trash')} Delete this board and its nested boards</button></div>`);$('#rename-board').onclick=renameBoard;$('#organize-board').onclick=()=>{$('#modal').close();arrange();};$('#clear-edges').onclick=()=>{$('#modal').close();change(()=>current().edges=[]);};$('#copy-board').onclick=()=>{$('#modal').close();change(()=>{const b=clone(current());b.id=uid();b.name+=' — copy';const map=new Map();b.cards.forEach(c=>{const old=c.id;c.id=uid();map.set(old,c.id);});b.edges=b.edges.map(e=>({...e,id:uid(),from:map.get(e.from),to:map.get(e.to)}));workspace.boards.push(b);workspace.active=b.id;selected.clear();});};$('#delete-board').onclick=()=>{modal('Delete this board?','Its nested boards and all their cards will also be removed. You can undo this.',`<div class="modal-footer"><button id="confirm-delete-board" class="button danger">Delete board</button></div>`);$('#confirm-delete-board').onclick=()=>{$('#modal').close();change(()=>{const doomed=new Set([current().id]);let grow=true;while(grow){grow=false;for(const b of workspace.boards)if(doomed.has(b.parent)&&!doomed.has(b.id)){doomed.add(b.id);grow=true;}}workspace.boards=workspace.boards.filter(b=>!doomed.has(b.id));for(const b of workspace.boards){const deleted=new Set(b.cards.filter(c=>doomed.has(c.boardId)).map(c=>c.id));removeCards(b,deleted);}if(!workspace.boards.length)workspace.boards.push(board());workspace.active=workspace.boards[0].id;selected.clear();});};};}
function editEdge(id){const e=current().edges.find(e=>e.id===id);modal('Connect the dots.','Give this connection a little meaning.',`<div class="field"><label for="edge-label">Label</label><input id="edge-label" value="${esc(e.label)}"></div><div class="modal-footer"><button class="button danger" id="edge-delete">Delete connection</button><button class="button primary" id="edge-save">Save label</button></div>`);$('#edge-save').onclick=()=>{const label=$('#edge-label').value;$('#modal').close();change(()=>e.label=label);};$('#edge-delete').onclick=()=>{$('#modal').close();change(()=>current().edges=current().edges.filter(x=>x.id!==id));};}
function showSearch(){modal('Find the thread.','Search across all boards, notes, tasks, and tags.',`<input class="text-input" id="search-query" placeholder="Search your workspace…" aria-label="Search workspace"><div class="search-results" id="search-results"></div>`);$('#search-query').focus();const query=()=>{const q=$('#search-query').value.toLowerCase().trim(),results=[];if(q)for(const b of workspace.boards){if((b.name+' '+b.description).toLowerCase().includes(q))results.push({b,title:b.name,type:'board'});for(const c of b.cards)if((c.title+' '+c.body+' '+c.tags.join(' ')+' '+c.items.map(i=>i.text).join(' ')+' '+c.comments.map(i=>i.text).join(' ')+' '+c.url).toLowerCase().includes(q))results.push({b,c,title:c.title,type:c.type});}$('#search-results').innerHTML=results.slice(0,100).map((r,i)=>`<button class="search-result" data-result="${i}">${icon(r.type)}<span><strong>${esc(r.title)}</strong><small>${esc(r.b.name)} · ${r.type}</small></span></button>`).join('')||`<p class="inline-note">${q?'No ideas found. Try another word.':'Your next discovery is a search away.'}</p>`;$('#search-results').querySelectorAll('[data-result]').forEach(btn=>btn.onclick=()=>{const r=results[btn.dataset.result];$('#modal').close();navigate(r.b.id);if(r.c){selected=new Set([r.c.id]);focusCard(r.c);render();}});};$('#search-query').oninput=query;query();}
function focusCard(c){const v=current().view,r=$('#canvas').getBoundingClientRect();v.x=r.width/2-(c.x+c.w/2)*v.zoom;v.y=r.height/2-(c.y+c.h/2)*v.zoom;view();dirty();}
function zoom(next,x,y){const v=current().view,r=$('#canvas').getBoundingClientRect();x??=r.width/2;y??=r.height/2;next=Math.min(2,Math.max(.2,next));v.x=x-(x-v.x)*next/v.zoom;v.y=y-(y-v.y)*next/v.zoom;v.zoom=next;view();dirty();}
function fit(){const cs=current().cards;if(!cs.length)return;const minX=Math.min(...cs.map(c=>c.x)),minY=Math.min(...cs.map(c=>c.y)),maxX=Math.max(...cs.map(c=>c.x+c.w)),maxY=Math.max(...cs.map(c=>c.y+c.h)),r=$('#canvas').getBoundingClientRect(),v=current().view;v.zoom=Math.min(1.2,Math.max(.2,Math.min((r.width-170)/(maxX-minX),(r.height-110)/(maxY-minY))));v.x=95-minX*v.zoom;v.y=35-minY*v.zoom;view();dirty();}
function svgExport(b){
 const cs=b.cards,minX=Math.min(0,...cs.map(c=>c.x))-25,minY=Math.min(0,...cs.map(c=>c.y))-25,maxX=Math.max(800,...cs.map(c=>c.x+c.w))+25,maxY=Math.max(600,...cs.map(c=>c.y+c.h))+25;
 const textLines=(text,x,y,width)=>{const words=String(text).split(/\s+/),lines=[];let line='';for(const word of words){if((line+' '+word).length>Math.max(15,Math.floor(width/7))){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);return lines.map((l,i)=>`<text x="${x}" y="${y+i*19}" fill="#66765c" font-size="12">${esc(l)}</text>`).join('');};
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minX} ${minY} ${maxX-minX} ${maxY-minY}"><style>text{font-family:Arial,sans-serif}</style><rect x="${minX}" y="${minY}" width="100%" height="100%" fill="#f7f8f2"/>`+b.edges.map(e=>{const f=cs.find(c=>c.id===e.from),t=cs.find(c=>c.id===e.to);return `<path d="M${f.x+f.w} ${f.y+f.h/2}L${t.x} ${t.y+t.h/2}" fill="none" stroke="#a3b094"/><text x="${(f.x+f.w+t.x)/2}" y="${(f.y+f.h/2+t.y+t.h/2)/2-8}" fill="#7a876a" font-size="10">${esc(e.label)}</text>`;}).join('')+[...cs].sort((a,b)=>(a.type==='column'?-1:0)-(b.type==='column'?-1:0)).map(c=>`<g><rect x="${c.x}" y="${c.y}" width="${c.w}" height="${c.h}" rx="6" fill="${colors[c.color]||'#fff'}" stroke="#d8e0ce"/><clipPath id="clip-${c.id}"><rect x="${c.x+2}" y="${c.y+2}" width="${c.w-4}" height="${c.h-4}"/></clipPath><g clip-path="url(#clip-${c.id})">${['image','sketch'].includes(c.type)&&c.media?`<image href="${esc(c.media)}" x="${c.x}" y="${c.y+40}" width="${c.w}" height="${c.h-40}" preserveAspectRatio="xMidYMid meet"/>`:''}<text x="${c.x+18}" y="${c.y+29}" font-size="${c.type==='heading'?20:14}" font-weight="bold" fill="#364b2d">${esc(c.title)}</text>${textLines(c.type==='task'?c.items.map(i=>(i.done?'✓ ':'□ ')+i.text).join(' / '):c.type==='board'?'Nested board: '+workspace.boards.find(b=>b.id===c.boardId)?.name:c.body+(c.url?' '+c.url:''),c.x+18,c.y+58,c.w-36)}</g></g>`).join('')+'</svg>';
}
function showExport(){modal('Take your ideas with you.','Portable files. No account required.',`<div class="export-options"><button class="export-option" data-export="json">${icon('board')}<span><strong>Workspace backup · JSON</strong><small>All boards, embedded files, and annotations. Re-import to restore.</small></span></button><button class="export-option" data-export="svg">${icon('image')}<span><strong>Current board · SVG</strong><small>A scalable visual snapshot of cards and connections.</small></span></button><button class="export-option" data-export="md">${icon('note')}<span><strong>Current board · Markdown</strong><small>Notes, links, tags, and checklists as plain text.</small></span></button><button class="export-option" id="import-backup">${icon('download')}<span><strong>Import workspace backup</strong><small>Replaces this workspace. Export your current work first.</small></span></button></div>`);$('#modal').querySelectorAll('[data-export]').forEach(btn=>btn.onclick=async()=>{const type=btn.dataset.export,b=current(),name=(type==='json'?'atelier-workspace':b.name.replace(/[^a-z0-9_-]/gi,'-'))+'.'+type;try{const ok=await storage.exportFile(name,type==='json'?JSON.stringify(workspace,null,2):type==='md'?markdown(b):svgExport(b),type==='json'?'application/json':type==='svg'?'image/svg+xml':'text/markdown');if(ok)toast('Export saved.');}catch(e){toast(e.message||e);}});$('#import-backup').onclick=()=>{$('#modal').close();$('#import-input').click();};}
async function importBackup(file){if(!file)return;if(file.size>100*1024*1024){toast('Backup exceeds 100 MB.');return;}try{const incoming=validate(JSON.parse(await file.text()));modal('Replace the current workspace?','Export a backup first if you want to keep a separate copy. This action can also be undone.',`<p>${incoming.boards.length} boards ready to import.</p><div class="modal-footer"><button class="button primary" id="confirm-import">Import workspace</button></div>`);$('#confirm-import').onclick=()=>{$('#modal').close();loadFailed=false;change(()=>{workspace=incoming;selected.clear();});toast('Workspace imported.');};}catch(e){toast('Could not import: '+e.message);}}
async function addFiles(files,point){
 const input=$('#media-input'),replace=input.dataset.replace;delete input.dataset.replace;delete input.dataset.type;const added=[];
 const modelFiles=files.filter(f=>isModel(f.name)),resources=[];if(modelFiles.length){if(files.length>100)throw Error('Select at most 100 model resources.');for(const f of files.filter(f=>!isModel(f.name))){if(f.size>15*1024*1024)throw Error(f.name+' exceeds 15 MB.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(f);});resources.push({name:f.webkitRelativePath||f.name,data:data.replace(/^data:[^;]*;/,'data:application/octet-stream;')});}files=modelFiles;}
 for(const f of files){if(f.size>(isModel(f.name)?50:15)*1024*1024){toast(`${f.name} exceeds the ${isModel(f.name)?50:15} MB limit.`);continue;}let type=isModel(f.name)?'model':f.type.startsWith('image/')?'image':f.type.startsWith('video/')?'video':'file';let media=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(f);});
 if(!/^data:(image\/(png|jpeg|webp|gif)|video\/(mp4|webm|ogg)|application\/pdf|text\/plain);base64,/.test(media)){if(type!=='file'&&type!=='model'){toast('Unsupported media type: '+f.name);continue;}media=media.replace(/^data:[^;]*;/,'data:application/octet-stream;');}
 const c=replace?clone(current().cards.find(c=>c.id===replace)):card(type,point?.x??100+(added.length%3)*280,point?.y??100+Math.floor(added.length/3)*250);if(!c)continue;c.type=type;c.media=media;c.filename=f.name;if(type==='model'){c.assets=resources;c.w=300;c.h=220;}c.title=f.name.replace(/\.[^.]+$/,'');if(type==='image'){const img=new Image();img.src=media;try{await img.decode();c.h=Math.min(500,Math.max(180,c.w*img.height/img.width+40));}catch{toast('Image could not be decoded.');continue;}}added.push(c);if(replace)break;
 }
 if(added.length){const candidate=clone(workspace),b=candidate.boards.find(b=>b.id===candidate.active);if(replace)b.cards=b.cards.map(c=>c.id===replace?added[0]:c);else b.cards.push(...added);if(new TextEncoder().encode(JSON.stringify(candidate)).length>100*1024*1024){toast('Adding these files would exceed the 100 MB workspace limit.');return;}change(()=>{workspace=candidate;selected=new Set(added.map(c=>c.id));});toast(added.length===1?'Reference added.':`${added.length} references added.`);}
 input.value='';
}
function sketch(existing){modal('Think with your hands.','A quick sketch can say more than a paragraph.',`<div class="sketch-tools"><label>Ink <input type="color" id="sketch-color" value="#456754"></label><label>Size <input type="range" id="sketch-size" min="1" max="20" value="3"></label><button class="button" id="sketch-clear">Clear</button></div><canvas id="sketch-canvas" width="1000" height="650"></canvas><div class="modal-footer"><button id="save-sketch" class="button primary">Add to board</button></div>`);const canvas=$('#sketch-canvas'),ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);let draw=false;const pos=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];};canvas.onpointerdown=e=>{draw=true;canvas.setPointerCapture(e.pointerId);ctx.beginPath();ctx.moveTo(...pos(e));};canvas.onpointermove=e=>{if(!draw)return;ctx.strokeStyle=$('#sketch-color').value;ctx.lineWidth=Number($('#sketch-size').value);ctx.lineCap='round';ctx.lineTo(...pos(e));ctx.stroke();};canvas.onpointerup=canvas.onpointercancel=()=>draw=false;$('#sketch-clear').onclick=()=>{ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);};$('#save-sketch').onclick=()=>{const data=canvas.toDataURL('image/png');$('#modal').close();change(()=>{const c=existing||card('sketch',100,100);c.media=data;c.w=350;c.h=265;if(!existing)current().cards.push(c);selected=new Set([c.id]);});};}
async function settings(){const rs=await storage.revisions();modal('Your space. Your rules.','Small adjustments for the way you work.',`<div class="field"><label for="setting-name">Name for annotations</label><input id="setting-name" value="${esc(localStorage.getItem('atelier-name')||'You')}"></div><div class="field"><label><input id="dark-setting" type="checkbox" ${document.body.classList.contains('dark')?'checked':''} style="width:auto"> Dark workspace</label><label><input id="snap-setting" type="checkbox" ${localStorage.getItem('atelier-snap')==='yes'?'checked':''} style="width:auto"> Snap cards to grid</label></div><p class="inline-note">${storage.isNative()?'Desktop edition · Rust + SQLite. Recovery snapshots are retained automatically.':'Browser preview · IndexedDB. Desktop edition uses Rust + SQLite.'}</p>${rs.length?'<div class="label">Recovery snapshots</div>'+rs.map(r=>`<button class="export-option" data-revision="${r.id}" style="width:100%;margin-top:8px">${icon('undo')} ${esc(r.created)} UTC</button>`).join(''):''}<div class="modal-footer"><button id="save-settings" class="button primary">Save preferences</button></div>`);$('#save-settings').onclick=()=>{localStorage.setItem('atelier-name',$('#setting-name').value||'You');localStorage.setItem('atelier-dark',$('#dark-setting').checked?'yes':'no');localStorage.setItem('atelier-snap',$('#snap-setting').checked?'yes':'no');document.body.classList.toggle('dark',$('#dark-setting').checked);$('#modal').close();};$('#modal').querySelectorAll('[data-revision]').forEach(btn=>btn.onclick=async()=>{try{const restored=validate(JSON.parse(await storage.restoreRevision(Number(btn.dataset.revision))));modal('Restore this snapshot?','Current changes will be replaced. You can undo the restore.',`<div class="modal-footer"><button class="button primary" id="restore-confirm">Restore</button></div>`);$('#restore-confirm').onclick=()=>{$('#modal').close();change(()=>{workspace=restored;selected.clear();});};}catch(e){toast(e.message||e);}});}
function help(){modal('Keep the flow.','Keyboard shortcuts',`<div class="shortcuts">${[['New note','N'],['New checklist','T'],['New link','L'],['Connect cards','C'],['Search workspace','⌘ / Ctrl K'],['Undo / redo','⌘ Z / ⌘ ⇧ Z'],['Select all cards','⌘ / Ctrl A'],['Duplicate selected','⌘ / Ctrl D'],['Copy / paste selected','⌘ C / ⌘ V'],['Delete selected','Backspace / Delete'],['Select several cards','Shift + click'],['Pan canvas','Space + drag / middle drag'],['Zoom canvas','Ctrl + scroll'],['Fit board','F'],['Edit card','Double-click / Enter'],['Clear selection','Escape']].map(([a,b])=>`<span>${a}</span><kbd>${b}</kbd>`).join('')}</div><p class="inline-note" style="margin-top:25px">Atelier is a standalone local workspace. Cloud sync, real-time collaboration, web clipping, and online previews are not included in this release.</p>`);}
function undo(){if(!history.past.length)return;workspace=history.undo(workspace);selected.clear();dirty();render();}
function redo(){if(!history.future.length)return;workspace=history.redo(workspace);selected.clear();dirty();render();}
function bind(){
 hydrate();renderTools();$('#new-board').onclick=()=>newBoard();$('#templates-open').onclick=showTemplates;$('#search-open').onclick=showSearch;$('#board-title').ondblclick=$('#board-description').ondblclick=renameBoard;$('#board-menu').onclick=boardMenu;$('#undo').onclick=undo;$('#redo').onclick=redo;$('#export-open').onclick=showExport;$('#settings-open').onclick=()=>settings().catch(e=>toast(e.message));$('#help-open').onclick=help;$('#first-note').onclick=()=>add('note');$('#zoom-in').onclick=()=>zoom(current().view.zoom+.1);$('#zoom-out').onclick=()=>zoom(current().view.zoom-.1);$('#zoom-label').onclick=()=>zoom(1);$('#fit').onclick=fit;
 $('#media-input').onchange=e=>addFiles([...e.target.files]).catch(e=>toast(e.message));$('#import-input').onchange=e=>{importBackup(e.target.files[0]);e.target.value='';};
 const canvas=$('#canvas');canvas.ondblclick=e=>{if(e.target===canvas||e.target.id==='world'||e.target.id==='cards')add('note',position(e));};
 canvas.addEventListener('pointerdown',e=>{if(e.button===1||space){e.preventDefault();const start={x:e.clientX,y:e.clientY},v=current().view,before={x:v.x,y:v.y};canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';const move=ev=>{v.x=before.x+ev.clientX-start.x;v.y=before.y+ev.clientY-start.y;view();};const end=()=>{canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',end);canvas.removeEventListener('pointercancel',end);canvas.style.cursor='';dirty();};canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);}else if(!e.target.closest('.card,#tools,.canvas-bottom')){selected.clear();renderCards();renderInspector();}});
 canvas.addEventListener('wheel',e=>{e.preventDefault();if(e.ctrlKey||e.metaKey){const r=canvas.getBoundingClientRect();zoom(current().view.zoom*Math.exp(-e.deltaY*.003),e.clientX-r.left,e.clientY-r.top);}else{current().view.x-=e.deltaX;current().view.y-=e.deltaY;view();dirty();}},{passive:false});
 canvas.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';};canvas.ondrop=e=>{e.preventDefault();if(e.dataTransfer.files.length)addFiles([...e.dataTransfer.files],position(e)).catch(e=>toast(e.message));else{const text=e.dataTransfer.getData('text/uri-list')||e.dataTransfer.getData('text/plain');if(text){const c=card(/^https?:\/\//.test(text)?'link':'note',position(e).x,position(e).y);if(c.type==='link'){c.url=text;c.title='Saved link';}else c.body=text;change(()=>{current().cards.push(c);selected=new Set([c.id]);});}}};
 document.addEventListener('keydown',e=>{
  const editing=e.target.closest('input,textarea,select,[contenteditable]');if($('#modal').open)return;
  if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showSearch();return;}if(editing)return;
  if(e.code==='Space'){e.preventDefault();space=true;canvas.style.cursor='grab';return;}
  const cmd=e.metaKey||e.ctrlKey,k=e.key.toLowerCase();if(cmd&&k==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(cmd&&k==='y'){e.preventDefault();redo();}else if(cmd&&k==='a'){e.preventDefault();selected=new Set(current().cards.map(c=>c.id));renderCards();renderInspector();}else if(cmd&&k==='d'){e.preventDefault();change(()=>selected=new Set(duplicateCards(current(),selected)));}else if(cmd&&k==='c'){e.preventDefault();clipboard=clone(current().cards.filter(c=>selected.has(c.id)));toast(`${clipboard.length} cards copied.`);}else if(cmd&&k==='v'&&clipboard.length){e.preventDefault();change(()=>{const copies=clone(clipboard).map(c=>({...c,id:uid(),x:c.x+40,y:c.y+40}));current().cards.push(...copies);selected=new Set(copies.map(c=>c.id));});}else if(cmd&&k==='s'){e.preventDefault();persist();}else if(e.key==='Backspace'||e.key==='Delete'){e.preventDefault();deleteSelected();}else if(e.key==='Escape'){selected.clear();connectMode=false;connectFrom=null;render();renderTools();}else if(e.key==='Enter'&&selected.size){renderInspector();$('#edit-title')?.focus();}else if(!cmd){if(k==='n')add('note');if(k==='t')add('task');if(k==='l')add('link');if(k==='f')fit();if(k==='c'){connectMode=!connectMode;connectFrom=null;renderTools();}}
 });document.addEventListener('keyup',e=>{if(e.code==='Space'){space=false;canvas.style.cursor='';}});window.addEventListener('blur',()=>{space=false;canvas.style.cursor='';});
 document.addEventListener('paste',e=>{if(e.target.closest('input,textarea')||$('#modal').open)return;const files=[...e.clipboardData.files];if(files.length){e.preventDefault();addFiles(files).catch(e=>toast(e.message));}});
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){clearTimeout(saveTimer);persist();}});
}
try{workspace=await storage.load()||initial();}catch(e){workspace=initial();loadFailed=true;setTimeout(()=>{toast('Saved workspace could not be loaded. Your saved data has been preserved.');modal('Your saved work needs attention.','Automatic saving is paused to preserve the existing workspace.',`<p class="inline-note">${esc(e.message||e)}. Import a valid backup to recover, or explicitly start a new workspace.</p><div class="modal-footer"><button class="button" id="recover-import">Import backup</button><button class="button danger" id="recover-new">Start new workspace</button></div>`);$('#recover-import').onclick=()=>{$('#modal').close();$('#import-input').click();};$('#recover-new').onclick=()=>{$('#modal').close();loadFailed=false;persist();};},100);}
document.body.classList.toggle('dark',localStorage.getItem('atelier-dark')==='yes');bind();render();if(!loadFailed)persist();

if(storage.isNative()){const win=window.__TAURI__.window.getCurrentWindow();let closing=false;win.onCloseRequested(async event=>{event.preventDefault();if(closing)return;closing=true;clearTimeout(saveTimer);if(loadFailed||await persist())await win.destroy();else closing=false;}).catch(e=>toast('Close protection unavailable: '+String(e)));}
